### ISSUE TITLE
'error running cerbot' when trying to enable https with lets-encrypt 

### ISSUE THREAD

**Issue by jbdv-ife** [nextcloud/nextcloud-snap#282] opened 2017-05-23 18:16 UTC
I am trying to enable https for my nextcloud box using the built in command line utility, but certbot fails while attempting to obtain certificates, with what seems to be a python error?

I run the following command:
`sudo nextcloud.enable-https lets-encrypt`
and enter the following information:
`Have you met these requirements? (y/n) y`
`Please enter an email address (for urgent notices or key recovery): someaddress@gmail.com`
`Please enter your domain name(s) (space-separated): mydomain.no`

Then the following error appears:
`Attempting to obtain certificates... error running certbot:`
`Traceback (most recent call last):`
`File "/snap/nextcloud/1333/bin/certbot", line 11, in <module>`
`    sys.exit(main())`
`File "/snap/nextcloud/1333/lib/python2.7/site-packages/certbot/main.py", line 735, in main`
`    args = cli.prepare_and_parse_args(plugins, cli_args)`
`File "/snap/nextcloud/1333/lib/python2.7/site-packages/certbot/cli.py", line 892, in prepare_and_parse_args`
`    helpful.add_deprecated_argument("--agree-dev-preview", 0)`
`  File "/snap/nextcloud/1333/lib/python2.7/site-packages/certbot/cli.py", line 572, in add_deprecated_argument`
`    self.parser.add_argument, argument_name, num_args)`
`  File "/snap/nextcloud/1333/lib/python2.7/site-packages/certbot/util.py", line 388, in add_deprecated_argument`
`    configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(ShowWarning)`
`AttributeError: 'tuple' object has no attribute 'add'`

Any ideas on how I can resolve this problem? I am using Snappy Ubuntu Core on a raspberry pi 2 with the following system setup:
`$ snap list`
`Name        Version       Rev   Developer  Notes`
`core        16-2          1690  canonical  -`
`nextcloud   11.0.3snap2   1333  nextcloud  -`
`pi2         16.04-0.17    29    canonical  -`
`pi2-kernel  4.4.0-1030-3  22    canonical  -`

**Comment by kyrofa** [comment] 2017-05-23 18:20
This is a duplicate of #279, but thank you for confirming! I'm investigating.

**Closed by kyrofa** 2017-05-23 18:20 UTC
