### ISSUE TITLE
Snap Compatibility issues with apps sharing mariadb server

### ISSUE THREAD

**Issue by ml48603** [nextcloud/nextcloud-snap#1330] opened 2020-05-05 23:06 UTC
When next cloud bookmarks app was modified by the developers recently the app broke, no auth. My NC server is installed as a snap.  After the app code had been repaired by the developers, the app still wouldn't auth from within  the snap installation. The app is working in nc manual installations.   Does this type of situation require the nextcloud snap to be reinstalled?  Do other apps that also use the mariadb server within the snap cause the same troubles and necessitate a reinstallation of the nc snap?  My snap was installed according to next cloud instructions at the nc site

**Comment by ml48603** [comment] 2020-05-05 23:09
Followup: Is there a way to disallow next cloud from updating apps automatically to prevent crashes of unproven new apps ?

**Comment by kyrofa** [comment] 2020-06-05 22:20
I'm sorry @ml48603. I haven't responded to this issue because, frankly, I'm completely unclear what the issue is. Can you please clarify?

**Comment by kyrofa** [comment] 2020-06-20 18:52
I'll go ahead and close this, but we can reopen if you're able to clarify what the issue is.

**Closed by kyrofa** 2020-06-20 18:52 UTC
