### ISSUE TITLE
snap refresh fails due to illegal version number

### ISSUE THREAD

**Issue by janschreier** [nextcloud/nextcloud-snap#1505] opened 2020-10-15 15:05 UTC
I am on Nextcloud 18/edge at the moment.
when I run 

    sudo snap refresh

I get the following error

> error: cannot perform the following tasks:
> Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": /snap/nextcloud/23790/bin/run-snap-migrations: 48: /snap/nextcloud/23790/bin/run-snap-migrations: Illegal number: 18-2020-10-15)

I guess it is related to the recent changes in run-snap-migrations 

when I run  

    snap list

i get the following results:

> Name       Version        Rev    Tracking       Publisher   Notes
> core       16-2.47        10126  latest/stable  canonical✓  core
> core18     20200724       1885   latest/stable  canonical✓  base
> nextcloud  18-2020-10-12  23683  18/edge        nextcloud✓  -

so it seems that lines 44 to 48 in https://github.com/nextcloud/nextcloud-snap/blob/master/src/migrations/bin/run-snap-migrations have some expectations which are not met (at least by my installation).

Thanks in advance for looking into this.

**Comment by leetxyz** [comment] 2020-10-17 17:29
Same Error on 19/edge when trying to update to latest 19 or when trying to update to 20/edge. I'm stuck on build `Nextcloud 19.0.4RC1 Build:2020-10-03T23:44:06+00:00`

> snap list

>Name Version Rev Tracking Publisher Notes
>core 16-2.47 10126 latest/stable canonical✓ coresnap 
>core18 20200724 1885 latest/stable canonical✓ base
>nextcloud 19-2020-10-04 23521 19/edge nextcloud✓ -

This is the output:

> snap refresh
> Copy snap "nextcloud" data
> Consider re-refresh of "nextcloud"
> error: cannot perform the following tasks:
> Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": /snap/nextcloud/23819/bin/run-snap-m igrations: 
>48: /snap/nextcloud/23819/bin/run-snap-migrations: Illegal number: 19-2020-10-17)

There is no folder "23819" in /snap/nextcloud/ only "23392", "23521" and "current" which links to "23521".

**Comment by kyrofa** [comment] 2020-10-18 16:24
Ah I know what this is, will fix soon

**Comment by kyrofa** [comment] 2020-10-19 22:12
This has been fixed by #1511, but it won't take effect until the next daily build (about 5 hours from now). I'm going to close this since I believe it's addressed, but if you continue to see this in the coming days, please re-open.

**Closed by kyrofa** 2020-10-19 22:12 UTC

**Comment by kyrofa** [comment] 2020-10-20 03:46
Argh, the daily build in `edge` is failing for another reason now, we're [trying to sort it out](https://twitter.com/rainveil/status/1318395682105872386). Once THAT is fixed, we should be good.

**Comment by leetxyz** [comment] 2020-10-20 09:39
Just did a snap refresh, update works again!
Thanks for your quick help.

**Comment by tensau** [comment] 2020-10-25 16:31
Sadly, doesn't work for me yet :(
I'm on NC 18, and getting this error: `Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": /snap/nextcloud/23743/bin/run-snap-migrations: 48: /snap/nextcloud/23743/bin/run-snap-migrations: Illegal number: 18-2020-06-23`

**Comment by kyrofa** [comment] 2020-10-25 22:04
@tensau that sounds like you're trying to refresh from `18/edge` back to `18/stable`, is that correct? I didn't think about that case, or I wouldn't have marked this "fixed" yet, because it needs to be contained in a release. Hang tight for #1523 and you'll be able to do that.

**Comment by kyrofa** [comment] 2020-10-26 01:47
Alright @tensau, try again now.

**Comment by tensau** [comment] 2020-10-26 06:17
Thank you very much for the fast response @kyrofa - this was the case and the fix did work :)

**Comment by locknut** [comment] 2021-08-09 09:01
@kyrofa sorry for resurrecting this old issue, but I think the problem still exists:

```
root@i-eb549fa0:/snap# snap list  nextcloud
Name       Version        Rev    Tracking  Publisher   Notes
nextcloud  18-2021-05-15  27832  18/edge   nextcloud✓  -
root@i-eb549fa0:/snap# snap refresh --channel=19/stable nextcloud
error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support skipping major versions, you must upgrade to Nextcloud 18 first. Try 'sudo snap refresh nextcloud --channel=18')
root@i-eb549fa0:/snap# 
```

Any suggestions?

**Comment by kyrofa** [comment] 2021-08-09 17:23
@locknut confirmed, can you please open a new issue while I knock out the fix?
