### ISSUE TITLE
Integrate collabora in nextcloud snap ?

### ISSUE THREAD

**Issue by skollrc** [nextcloud/nextcloud-snap#606] opened 2018-06-12 19:38 UTC
Hi all,

Is there a possibility to have collabora integrated in nextcloud snap ? It's look impossible to have a nextcloud snap and collabora in the same server :-/

**Comment by r4co0n** [comment] 2018-06-18 16:30
This issue is a duplicate of #104 and its siblings, I'm closing it.

The end result is: Collabora needs to be packaged as a snap and shipped via the store, this is not an issue here. If you install Collabora in any way, you should be able to point the nextcloud addon to the appropriate url and you're good to go. I see why also shipping this as a snap would be beneficial to end-users, but that's really just out-of-scope for this project.

**Closed by r4co0n** 2018-06-18 16:30 UTC
