### ISSUE TITLE
Cannot configure listening IP address for my nextcloud-snap

### ISSUE THREAD

**Issue by bithex** [nextcloud/nextcloud-snap#405] opened 2017-12-27 17:17 UTC
I just installed the nextcloud snap on Ubuntu Server 16.04 and all works like a snap.
However, the httpd binds/listens to all IP addresses on my server, and it turns out the ports.http and ports.https hooks do not accept parameters with IP addresses in them, like "12.34.56.78:80" and "12.34.56.78:443". 
Looks like it's not possible to bind the nextcloud snap to only one specific IP address like the Apache "Listen" directive is supposed to allow (e.g. in httpd.conf, ssl.conf).

Could you please add functionality or a new hook to allow configuration of the listening IP address/interface, e.g. like:
"snap set nextcloud ports.http=12.34.56.78:80", "snap set nextcloud ports.https=12.34.56.78:443"
or maybe like:
"snap set nextcloud address.http=12.34.56.78", "snap set nextcloud address.https=12.34.56.78"

I guess a similar issue was filed earlier, perhaps not quite the same, see https://github.com/nextcloud/nextcloud-snap/issues/331

**Comment by kyrofa** [comment] 2017-12-29 18:58
Yeah, dupe of #331. I'll get to it once I have some time. If you have some time to look into it, please do!

**Closed by kyrofa** 2017-12-29 18:58 UTC

**Comment by bithex** [comment] 2017-12-29 21:17
Okay, I'll have a look at it.

Which method do you propose?
Perhaps "snap set nextcloud address.http=12.34.56.78" and "snap set nextcloud address.https=12.34.56.78" is more natural, since the user would be able to change addresses at will without specifying the port numbers again?

I guess implementing IP6 would be good as well, as per https://httpd.apache.org/docs/2.4/bind.html

**Comment by kyrofa** [comment] 2017-12-30 23:02
Can you think of a use-case where one wants the snap to listen on different interfaces for HTTP versus HTTPS?

**Comment by bithex** [comment] 2017-12-31 18:54
Well, The Listen directive is set in two places/files which are src/apache/conf/httpd.conf and src/apache/conf/ssl.conf respectively.

At least, there three obvious use cases:
1 - The user has his snap listening on the same address on both http/80 and https/443.
2 - The user has his snap listening only on http/80, in which case the Listen directive for https must not be set.
3 - The user has his snap listening only on https/443, in which case the Listen directive for http must not be set.

A 4th use-case of the snap listening on both http/80 and https/443, but on a different address for each, is a possibility but highly unlikely.

In light of 2 and 3 I guess the listening address must be set for http and https individually.
But, I'm a little confused, does the ssl.conf take over if the user is using https? 
Looking at your commit https://github.com/nextcloud/nextcloud-snap/commit/397d361549774e1e232517706dc4bfd4457aaf5f, it looks like both http and https are set in the ssl.conf file?
Do you propose something like "snap set nextcloud address=12.34.56.78" will suffice, in which case the Listen directive is set in both places/files?

**Comment by kyrofa** [comment] 2018-01-02 16:41
>  But, I'm a little confused, does the ssl.conf take over if the user is using https?

It doesn't take over, but it's only included IF the user is using HTTPS. See the logic [here](https://github.com/nextcloud/nextcloud-snap/blob/master/src/apache/conf/httpd.conf#L194). There are only two possible use-cases today in the snap:

1. The user doesn't have HTTPS enabled, in which case the snap is only listening on the HTTP port (by default port 80).
2. The user has HTTPS enabled, in which case the snap is listening on both the HTTP and HTTPS port, with the HTTP port redirecting to the HTTPS port (this is why you also see the HTTP port used in ssl.conf).

I still can't think of a reason to have a different interface for each, so I say we only support one, which affects the Listen directive in both places.

**Comment by kyrofa** [comment] 2018-12-22 05:01
Did you search the wiki for this? You can simply change the ports.

**Comment by NESC1US** [comment] 2020-11-01 14:00
> Did you search the wiki for this? You can simply change the ports.

Yes, but that means that url gets rewritten and reverse proxy is then bypassed.

There is sudo snap set nextcloud address.https=127.0.0.1
But that does nothing.. 

i am frustrated by this and will have to install nextcloud natively, snap is like windows - easy to start, very hard to optimize.

**Comment by kyrofa** [comment] 2020-11-01 15:59
> There is sudo snap set nextcloud address.https=127.0.0.1
> But that does nothing..

That has _never_ done anything, where are you seeing that?

**Comment by dudalov** [comment] 2022-03-28 19:22
> > There is sudo snap set nextcloud address.https=127.0.0.1
> > But that does nothing..
> 
> That has _never_ done anything, where are you seeing that?

like, really? there are still no way to force nextcloud snap to listen only one ip address?

**Comment by y0va** [comment] 2023-02-20 23:21
This is still not solved.
