### ISSUE TITLE
Missing SMB support

### ISSUE THREAD

**Issue by sfabel** [nextcloud/nextcloud-snap#548] opened 2018-05-06 07:31 UTC
By default, external SMB shares are not accessible when installing the Nextcloud snap. Please publish steps to include SMB or add support to the snap.

**Comment by pachulo** [comment] 2018-05-06 10:46
Yeah, we did try to add SMB support last year, but there was a problem with armhf devices (rbpi at least) 
https://github.com/nextcloud/nextcloud-snap/issues/272 https://github.com/nextcloud/nextcloud-snap/pull/263

Maybe we should try again now...

**Comment by kyrofa** [comment] 2018-05-07 14:43
@pachulo want to take another run at that, see if things have changed?

**Comment by pachulo** [comment] 2018-05-07 18:26
hey! yeah, I was thinking about that, but wanted to wait till the update to 13.x was done...anyway, I will try to find some time this week!

**Comment by kyrofa** [comment] 2018-05-07 18:28
Waiting for v13 is fine, too. Things will soon be fixed upstream for that, next point release I imagine.

**Comment by pachulo** [comment] 2018-05-14 22:04
I did try it again, but it seems that we won't be able to do it (without hackery) till snapcraft 2.43? is released witth your fix https://github.com/snapcore/snapcraft/pull/2112 for this kind of errors: 

```
Failed to stage: Parts 'certbot-nextcloud-plugin' and 'libsmbclient' have the following files, but with different contents:
    usr/lib/python2.7/UserString.py
    usr/lib/python2.7/base64.py
    usr/lib/python2.7/cProfile.py
    usr/lib/python2.7/cgi.py

...
```

**Comment by tomharristech** [comment] 2018-05-24 12:34
I've just installed v13, it's still broken. Is there a way I can just install smbclient manually?

**Comment by pachulo** [comment] 2018-05-24 22:06
I think that you will have to wait for somebody to integrate it into the snap @tomharristech :(

**Comment by skewty** [comment] 2018-06-10 15:21
I am sharing data on an SMB / CIFS share using the snap by mounting the share in `/etc/fstab` for now.

**Comment by 8GM-DK** [comment] 2018-07-03 11:58
@skewty How exactly are you doing this? I have a CIFS share mounted on /mnt/cloud and want it to be accessible in the cloud, but the external storage thing stays red. I mounted it with fir_mode and file_mode 0770, but to no avail. 

Any ideas?

**Comment by 8GM-DK** [comment] 2018-07-03 12:10
Okay, solved. To answer my own question: I need to mount the CIFS share under /media/xxxx. If I mounted it under /mnt/xxxx, it failed - even after running snap connect nextcloud:removable-media. But a CIFS mount under /media did the trick.

**Comment by jrtberlin** [comment] 2018-09-27 11:53
> I am sharing data on an SMB / CIFS share using the snap by mounting the share in `/etc/fstab` for now.
I have mounted the share as followed, nextcloud connects to the local /media/nas, but it does not show any file or folder. When I navigate via terminal into /media/nas everything seems to work properly. Any idea how to fix this?

//192.168.1.52/share /media/nas cifs username=myusername,password=mypassword,iocharset=utf8 0 0

**Comment by smartmeister** [comment] 2018-10-21 11:55
manually mounting the same share works great, using
`sudo mount -t cifs //192.168.1.52/share /media/nas -o username=my_username,password=my_password`

**Comment by BR0KK** [comment] 2019-07-03 10:25
SMB Support would be nice ... "smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login" is not possible. Please ask your system administrator to install it.

I get this error in the admin pannel --> external storage 

NC installed via SNAP today 
Installing php-smbclient does not do anything

**Comment by skewty** [comment] 2019-07-04 02:18
did you try installing smbclient at the OS level?

example: sudo apt install smbclient

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by BR0KK** [comment] 2019-07-06 12:32
No i dint try that as i dont know how to mount it afterwards.  On my Owncloud installs this feature is included and working ootb. 

installing samba, smbclient and php-smbclient with a reboot didn do anything to fix this in nextcloud

SMB is a mayor feature that is missing from nc  it needs to be implemented

**Comment by BR0KK** [comment] 2019-07-10 13:18
Tried mounting the share via cli but that gives me errors too.... Premission errors 13 and sec=ntlmv

Would this even be permanent (reboot, shutdowns etc) and can i access this share via the nextcloud webinterface (noobie access not administrator "cli" access ... i need to be able to use it like a normal network share...)?
I'd like to switch to nextcloud and would also like to use smb (like im used to from owncloud). but it seems that this is an issue not beeing looked at atm?

Why is this (everything) so 'effin complicated with linux ?

**Comment by BR0KK** [comment] 2019-07-12 12:33
I got the share mounted manually and via fstab (only) once and now it won't mount again.
I can update the the share to view my files but after the second reboot the share is empty. 

"sudo mount -a" throws error 22 at me 
Something about apparmour or premission denied  
Is there a timeline for features to be added ? 

I woud advise the devs of this repo to clearly state in the Readme that SMB is broken and not working in when you install via snap.

**Comment by szaimen** [comment] 2019-07-12 14:21
My fstab configuration is working without any problem on ubuntu 18.04 LTS.
I use the following entry in fstab:
//hostname/SMB-Share /media/directory cifs vers=3.0,username=yourusername,password=yourpassword,iocharset=utf8,file_mode=0770,dir_mode=0770 0 0

**Comment by BR0KK** [comment] 2019-07-15 16:03
Yay that worked thank you. I assume "filemode and dirmode" are premissions for the mountpoint?
Its works even after multiple reboots and powerdowns. Under "External Storage" i get a green light. 
 now i ned to obfuscate my passwords and im good to go 


Would still be nice to have this feature automated with nextcloud snap

**Comment by szaimen** [comment] 2019-07-15 17:28
No problem!
Yes, "filemode and dirmode" are permissions for the mountpoint and are applied when accessing the mounted files. (https://linux.die.net/man/8/mount.cifs) 
They are "must-haves" when accessing Windows-Network-Shares.

I agree that this functionality should definitely be included in the snap.
For the meantime a hint in [readme.md](https://github.com/nextcloud/nextcloud-snap/blob/master/README.md) would be nice. 
And possibly a Wiki-Entry on how to configure it manually.

**Comment by tl5k5** [comment] 2019-10-10 16:38
Any update on getting smb connectivity within the nextcloud snap?  Yes, I could mount in fstab, but I'd rather not.

**Comment by kyrofa** [comment] 2019-10-10 22:05
Dupe of #60

**Closed by kyrofa** 2019-10-10 22:05 UTC

**Comment by Capriatto** [comment] 2020-04-23 15:49
> My fstab configuration is working without any problem on ubuntu 18.04 LTS.
> I use the following entry in fstab: (you have to install cifs-utils first to get this working)
> 
> `//hostname/SMB-Share /media/directory cifs vers=3.0,username=yourusername,password=yourpassword,iocharset=utf8,file_mode=0770,dir_mode=0770 0 0`
> 
> I also enabled automatic refreshing for the mounted directories in the nextcloud external storage app.

If you got the mount error 95: (Operation not supported) try changing the version arg to 1.0

**Comment by ruedigerkupper** [comment] 2020-05-21 10:08
I believe this is not the same error. This report is about missing support for accessing CIFS shares in the snap. Which is a general restriction of snaps, it seems. Mounting the share manually to /media is just a workaround that makes Nextcloud think the share is removable media.

**Comment by abulka** [comment] 2021-07-30 03:45
After mounting the share as a local directory, and adding it to the nextcloud 'external storage app' settings, I found that Nextcloud couldn't read or write from `/media/directory` till I 

    sudo snap connect nextcloud:removable-media

which, to be fair, is in the the readme, but easy to miss.

**Comment by theowlfla** [comment] 2021-12-01 13:41
> After mounting the share as a local directory, and adding it to the nextcloud 'external storage app' settings, I found that Nextcloud couldn't read or write from `/media/directory` till I
> 
> ```
> sudo snap connect nextcloud:removable-media
> ```
> 
> which, to be fair, is in the the readme, but easy to miss.

You sir...are a legend !
