### ISSUE TITLE
Please update to a newer Nextcloud version

### ISSUE THREAD

**Issue by MadMacMig** [nextcloud/nextcloud-snap#1625] opened 2021-02-01 14:14 UTC
I would love it if their was a newer version of Nextcloud, because this is snap Nextcloud version 20.04 and the newest version is 20.06. I would just like to know when the next update will be coming.

**Comment by kyrofa** [comment] 2021-02-01 16:11
Dupe of #1619, it's coming soon.

**Closed by kyrofa** 2021-02-01 16:11 UTC
