### ISSUE TITLE
Use pretty URLs

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/nextcloud-snap#115] opened 2016-10-23 19:16 UTC
The Nextcloud snap should be configured to to use **https://cloud.nextcloud.com/apps/files/** instead of **https://cloud.nextcloud.com/index.php/apps/files/** ... This would also shorten the share URLs.

Hiding **index.php** in the URL is managed by redirection rules. 

Reference: 

https://docs.nextcloud.com/server/9/admin_manual/installation/source_installation.html#pretty-urls-label

https://www.youtube.com/watch?v=yqr22XG8P4w

**Comment by enoch85** [comment] 2016-10-24 09:43
From the ownCloud VM:

```

# Pretty URLs
echo "Setting RewriteBase to "/" in config.php..."
chown www-data:www-data $NCPATH/config/config.php
sudo -u www-data php $NCPATH/occ config:system:set htaccess.RewriteBase --value="/"
sudo -u www-data php $NCPATH/occ maintenance:update:htaccess
```

**Comment by HittingSmoke** [comment] 2016-10-25 14:18
@enoch85 But this won't work in the snap because the htdocs directory is not writable by anyone, right?

**Comment by oparoz** [comment] 2016-10-25 14:18
Correct, but that can be added to the script which launches Nextcloud.

**Comment by kyrofa** [comment] 2016-10-25 16:40
I think this is a dupe of #86, but this issue seems to be a little more alive so I'll ask my question here: Sounds like [there are issues caused](https://github.com/nextcloud/server/issues/1364) by this, no? Are we sure this is safe to enable for everyone? If it's safe, why isn't it done by default?

**Comment by jasonbayton** [comment] 2016-11-01 21:24
OK I looked into it on my instance, and the integrity check appears to be disabled by default. On that basis I don't think the issue presented in your link @kyrofa will impact this change, but will likely need to be checked in the future once the underlying issue is resolved.

**Comment by kyrofa** [comment] 2016-11-01 21:26
@jasonbayton that's likely a carry-over from the snap before v10.0.1 (when the Nextcloud in the snap was actually a fork). If you have v10.0.1 you can re-enable the integrity check (and indeed, if you installed the snap clean it would be enabled by default).

**Comment by jasonbayton** [comment] 2016-11-01 21:54
I'd hoped I could force-enable it myself by editing `/var/snap/nextcloud/current/config/.htaccess` but that appears to do a whole lot of nothing, as does `sudo nextcloud.occ maintenance:update:htaccess` presumably because the main `.htaccess` in `htdocs` is R/O.

**Comment by kyrofa** [comment] 2017-01-09 18:26
Closing due to inactivity. I'm not convinced this won't have ill side effects. When nextcloud enables this behavior by default, so can the snap.

**Closed by kyrofa** 2017-01-09 18:26 UTC
Labels: feature, needs info

**Comment by downeym** [comment] 2017-03-07 19:02
It seems that the bug of false positive integrity check (that was the concern expressed above) was fixed in December 2016, somewhere between the time of the last comment and the time this issue was closed. Is there any chance this issue can be revisited?

**Comment by kyrofa** [comment] 2017-03-07 19:10
@downeym I'm still uncomfortable with doing something by default that Nextcloud itself doesn't do.
