### ISSUE TITLE
Snap install doesn't allow `Transfer-Encoding: chunked` on PUT.

### ISSUE THREAD

**Issue by ncw** [nextcloud/nextcloud-snap#365] opened 2017-10-06 15:02 UTC
Snap install doesn't allow `Transfer-Encoding: chunked` on PUT.

This does work with an owncloud I have installed manually though, leading me to think that this is a problem with the snap packaging, in particular the webserver config.

For example

Without chunked transfer encoding

```
$ curl -X PUT --user user:pass --data @file.txt "https://nextcloud.example.com/remote.php/webdav/file.txt"
$ curl -X PROPFIND --user user:pass "https://nextcloud.example.com/remote.php/webdav/file.txt"
[snip]
    <d:getlastmodified>Fri, 06 Oct 2017 14:43:22 GMT</d:getlastmodified>
    <d:getcontentlength>5</d:getcontentlength>  <-------------- length 5
[snip]
```

And with chunked transfer encoding the upload is truncated to 0 bytes with no warning.

```
$ curl -X PUT --user user:pass --data @file.txt --header "Transfer-Encoding: chunked" "https://nextcloud.example.com/remote.php/webdav/file.txt"
$ curl -X PROPFIND --user user:pass "https://nextcloud.example.com/remote.php/webdav/file.txt"
[snip]
    <d:getlastmodified>Fri, 06 Oct 2017 14:43:39 GMT</d:getlastmodified>
    <d:getcontentlength>0</d:getcontentlength>  <-------------- length 0!
[snip]
```

A possibly related problem is discussed in the [SabreDav wiki](http://sabre.io/dav/clients/finder/) which says

> Finder uses Transfer-Encoding: Chunked in PUT request bodies. This is a little used HTTP feature, and therefore not implemented in a bunch of webservers. The only server I've seen so far that handles this reasonably well is Apache + mod_php. Nginx and Lighttpd respond with 411 Length Required, which is completely ignored by Finder. This was seen on nginx 0.7.63. It was recently reported that a development release (1.3.8) no longer had this issue.
> 
> When using this with Apache + FastCGI PHP completely drops the request body, so it will seem as if the PUT request was succesful, but the file will end up empty.

Diving down the rat-hole further I find [this php bug](https://bugs.php.net/bug.php?id=60826) which points the finger at apache's fast cgi implemention with [this bug](https://bz.apache.org/bugzilla/show_bug.cgi?id=53332).

The symptoms of the above seem to be that of using Apache with FastCGI but I'm not sure exactly what is used in the snap.  Is it possible to swap to using apache + mod_php?

**Comment by kyrofa** [comment] 2017-10-06 15:28
We were initially using mod_php, but switched to php-fpm a while back for more fine-grained control over performance. I suspect we'll have to wait for those bugs to be fixed :frowning_face: .

**Comment by gbrault** [comment] 2018-04-22 07:51
Hello there! Do we now if this is fixed now?

**Comment by r4co0n** [comment] 2018-05-15 14:27
The Apache bug blocking this issue is reported against `mod_fcgid`, not `mod_proxy_fcgi` which this snap is using.

Should this be re-raised against `mod_proxy_fcgi`?

**Comment by devurandom** [comment] 2018-06-10 10:38
Does anyone know what the current status for php-fpm + nginx / lighttpd is? Are they affected? If not, which version / configuration is necessary for this to work?

**Comment by e-alfred** [comment] 2018-08-10 11:53
Does this only apply to Apache/Nginx + PHP-FPM? Or does it affect mod_php too? If not, the rclone documentation is misleading because this would only affect the Snap package, but not Nextcloud in general.

**Comment by r4co0n** [comment] 2018-08-17 15:57
This is an Apache httpd-2 bug.

**Comment by e-alfred** [comment] 2019-06-08 10:58
The bug reffered in the original post was fixed in Apache by this patch: https://svn.apache.org/viewvc?view=revision&revision=1848298

Is this problem still relevant then?

**Comment by kyrofa** [comment] 2019-10-10 21:29
I'm going to go ahead and close this issue. We can't do anything about it other than wait for upstream components to fix it, which we update continually, so there isn't much value in continuing to track it here. Sounds like it probably has been fixed by now, anyway.

**Closed by kyrofa** 2019-10-10 21:29 UTC
Labels: upstream

**Comment by ylluminate** [comment] 2020-02-28 00:01
Has this been resolved?

**Comment by kyrofa** [comment] 2020-02-28 00:29
It sounds like it, but I haven't confirmed.

**Comment by gnoutchd** [comment] 2024-03-23 16:58
I just got bitten by this bug hard, as in my phone's backups (uploaded automatically via Davx5) were wrecked for weeks and it was only by luck that I noticed.

According to comments in nextcloud/server#7995, nextcloud/vm and a few other deployments have workarounds in place (something involving a `SetEnv proxy-sendcl` somewhere in the apache config).  Could the snap do the same thing?

**Comment by Drakonas** [comment] 2026-03-01 04:27
@ylluminate @kyrofa @ncw @r4co0n I wanted to chime in that @gnoutchd actually posted something useful this Snap team could do to work around this while we wait for the php-fpm team to address the real issue.

See the linked issue they posted. It mentions there's a change in the .htaccess they implemented that makes the chunk requests work by forced buffering:
https://github.com/nextcloud/server/issues/7995#issuecomment-3816221177

This was added to the main Nextcloud server. Could this be added to the snap .htaccess file too?

**Comment by kyrofa** [comment] 2026-03-01 15:17
@Drakonas [the snap already uses the `.htaccess` file from Nextcloud](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/snap/snapcraft.yaml#L182). Did you see the next comment that says it doesn't fix anything?

**Comment by gnoutchd** [comment] 2026-03-10 01:24
It seems to work though? I tried the test case from https://github.com/nextcloud/server/issues/7995 against my nextcloud-snap instance and it's fine now.  (Note that when I last tried this, the  `SetEnv proxy-sendcl` workaround hadn't been added to nextcloud/server yet. I think that happened in v30.0.0.)

I think @susnux was just observing that the workaround is only effective if you are using Apache.  That should be fine since the snap does use Apache.
