### ISSUE TITLE
Allow parallel instances of snap on same machine

### ISSUE THREAD

**Issue by jassonmc** [nextcloud/nextcloud-snap#1196] opened 2019-12-27 10:17 UTC
Environment: Fresh install, CentOS 7 Minimal, VM on Hyper-V, fully yum updated, EPEL enabled
(Works) Snap install nextcloud
(Works) Snap set nextcloud ports.https=444
(Works) Snap install nextcloud_instance2
(Fails) Snap set nextcloud_instance2 ports.https=445
error: cannot perform the following tasks:
Run configure hook of "nextcloud_instance2" snap (run hook "configure": error: error running snapctl: unknown service: "nextcloud.apache")

It seems as if the snaps config command is calling apache by a fixed name, rather then referencing it by its install name, in that example "nextcloud_instance2".
___
I would assume that this could be an easy fix to allow multiple instances of Nextcloud on the same machine. It is working already, just the reconfiguration as explained above does not work, which leaves the instanced installation stuck to it's config at install time, which means that it works, just without the possibility to easily enable https.
There are probably more areas in the Nextcloud snap tool set, which reference by snap name and not by install name, which would need to be adjusted accordingly of course.

**Comment by kyrofa** [comment] 2020-01-06 16:31
This is a duplicate of #1010, more details there.

**Closed by kyrofa** 2020-01-06 16:31 UTC
