### ISSUE TITLE
ResourceLocator can not find a web root on several extensions

### ISSUE THREAD

**Issue by asadana** [nextcloud/nextcloud-snap#902] opened 2019-02-19 13:36 UTC
### Server configuration

**Operating system**: Ubuntu 18.04.2

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from 14.0.6

**Where did you install Nextcloud from:** Snappy

</details>

**Are you using external storage, if yes which one:** Using S3 as primary storage

**Are you using encryption:** no

</details>

### Client configuration
**Browser:** Mozilla Firefox 65 and Google Chrome 72

**Operating system:** Linux (Ubuntu/Fedora) and Windows 10

#### Nextcloud error logs
<details>
<summary>Error log: Talk/Spreed</summary>

```
[lib] Error: ResourceLocator can not find a web root (root: /var/snap/nextcloud/11336/nextcloud/extra-apps/spreed, file: index.php/css/spreed/656a-c5cf-merged-files.css?v=f7fbce5eca1c766bdf8f93c3337c21ac, webRoot: , throw: true)

GET /index.php/apps/files/
from  200.00.200.200 by xxxx@xxx.com at 2019-02-18T16:11:30-05:00
```
</details>

<details>
<summary>Error log: Calendar</summary>

```
[lib] Error: ResourceLocator can not find a web root (root: /var/snap/nextcloud/11336/nextcloud/extra-apps/calendar, file: index.php/css/calendar/029b-c5cf-app.min.css?v=f7fbce5eca1c766bdf8f93c3337c21ac, webRoot: , throw: true)

GET /index.php/apps/calendar/
from  200.00.200.200 by yyyy@yyy.com at 2019-02-18T14:17:03-05:00
```
</details>

<details>
<summary>Error log: Deck</summary>

```
[lib] Error: ResourceLocator can not find a web root (root: /var/snap/nextcloud/11336/nextcloud/extra-apps/deck, file: index.php/css/deck/7822-c5cf-style.css?v=f7fbce5eca1c766bdf8f93c3337c21ac, webRoot: , throw: true)

GET /index.php/apps/deck/
from 200.00.200.200 by zzzz@zzz.com at 2019-02-18T13:50:15-05:00
```
</details>

**Comment by asadana** [comment] 2019-02-19 13:38
Possible duplicate of #625.

Spreed/Talk has had much more frequent errors than other two. Basically any use of Talk spawns these errors.
Calendar and deck errors are more sparsely seen.

**Comment by kyrofa** [comment] 2019-02-22 16:41
Thanks for this, @asadana. We had to fix a bug in upstream Nextcloud for this a while back, I think various apps have the bug as well.

**Comment by bn4t** [comment] 2019-03-11 10:17
Can confirm, this happens to me too. 
Additionally to the already listed apps the error also occurs for the collabora app.

**Comment by kyrofa** [comment] 2019-03-12 18:44
Please tell the individual apps about this, these are bugs in the apps, not the snap.

**Comment by Famku** [comment] 2019-03-13 18:06
confirm - same issue with Talk/Spreed

**Comment by nickvergessen** [comment] 2019-03-14 16:37
This should not be a bug in the apps, but in the way the config.php in the snap is.
It looks like the given webroot for the app directories is not correct/reachable from the web

**Comment by kyrofa** [comment] 2019-03-14 17:39
@nickvergessen we've dealt with this issue in the past in upstream Nextcloud, for example:

- https://github.com/nextcloud/server/pull/7257
- https://github.com/nextcloud/server/pull/7061

Nothing has changed in the snap to cause this, which leads me to suspect the apps themselves, unless something broke in Nextcloud itself again.

**Comment by sireebob** [comment] 2019-05-08 15:21
since devs can't agree on where the problem lies, it sounds like this will never get fixed in some apps. is it just cosmetic?

**Comment by robertsozolins** [comment] 2019-05-31 11:00
This problem has been around for more than a year, really can't fix it?

**Comment by kyrofa** [comment] 2019-05-31 14:43
I've tried to give guidance on how to fix it :man_shrugging: .

**Comment by the-sane** [comment] 2019-05-31 19:07
The dropit app I referenced above seems to function just fine despite this error being spammed in my logs.  For us as users, does that mean the error is inconsequential or is there some side effect that I'm just not seeing?

In https://github.com/nextcloud/spreed/issues/1615 , @nickvergessen definitively says it is not an issue with the talk app and points to the snap or how the server repo loads apps.  @kyrofa definitively says it isn't the snap.  Is there anything we can do to try to pinpoint the problem and get it in front of the right devs?

**Comment by kyrofa** [comment] 2019-05-31 19:19
> For us as users, does that mean the error is inconsequential or is there some side effect that I'm just not seeing?

First, a note that I am also a user. I also see these annoying messages in my logs. However, I also have noticed no ill effects, which is why I haven't taken it upon myself to fix these issues, regardless of what is causing them. I assure you I would, otherwise (as I have done for exactly this issue [in the past](https://github.com/nextcloud/nextcloud-snap/issues/902#issuecomment-472981857)).

If someone wants to take it upon themselves to get to the bottom of this, we'd all appreciate it I'm sure. The path I've taken in the past is to install Nextcloud on its own, without the snap, but with a config similar to the snap's. Specific details are given [here](https://github.com/nextcloud/server/pull/7061#issuecomment-343323438). Once you have that put together, you should be able to reproduce the issue. If so, you can literally start printing stuff out or putting things in the logs until you get to the bottom of where the code it going and why.

**Comment by the-sane** [comment] 2019-06-01 16:56
I appreciate the info, thank you!

**Comment by juliushaertl** [comment] 2019-07-11 08:32
This is most likely an issue of https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Template/ResourceLocator.php#L128 that doesn't detect the webroot properly if the apps directory is in a different place.

**Comment by szaimen** [comment] 2019-07-11 10:50
> This is most likely an issue of https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Template/ResourceLocator.php#L128 that doesn't detect the webroot properly if the apps directory is in a different place.

Nice to know and how can that be resolved? This issue is very annoying...

**Comment by the-sane** [comment] 2019-07-15 18:27
Is this the same issue? https://github.com/nextcloud/server/issues/13556

**Comment by kyrofa** [comment] 2019-07-15 18:42
Indeed, that setup is very similar to how the snap does things, and those log warnings are of course the same. I'd be willing to bet that it is the same issue.

**Comment by szaimen** [comment] 2019-07-24 09:28
>However, I also have noticed no ill effects, which is why I haven't taken it upon myself to fix these issues, regardless of what is causing them. 
@kyrofa I think I have to disaggree. It seems like when activating the dark mode over accessibility settings, a few buttons don't get shown in e.g. the text-app: [#187](https://github.com/nextcloud/text/issues/187)

**Comment by the-sane** [comment] 2019-08-05 17:01
So it turns out this may be more than just a cosmetic logging issue.  I didn't realize that the new text app was missing an entire toolbar for me until I saw the comment here:
https://github.com/nextcloud/text/issues/187#issuecomment-514387337

That toolbar is missing in both the default and dark themes for me though.

@kyrofa, you had mentioned you would like to know if the bug starts causing actual problems.  I tagged you in a summary post over on the server issue, but here's the stuff that may be relevant to us for the text app in particular.  The discussion begins at this comment:
https://github.com/nextcloud/text/issues/187#issuecomment-514609669

**Comment by acs-ferreira** [comment] 2019-09-08 12:25
I don't know if this is related, but i can't use the **Nextcloud Talk for Android** app, with many log lines like these one using this Snap (it just displays a loading animation).

No problem using a "manually" installed Nextcloud+Talk app.

**Comment by kyrofa** [comment] 2019-09-27 15:14
@the-sane I'm sorry for the delay-- thank you for tagging me over there, and for the very helpful comment.

**Comment by the-sane** [comment] 2019-09-30 14:49
v17 has been released and has made the new text editor the default for all installs.  Due to the broken toolbar we'd experience, this should probably be sorted out before pushing it to stable.  I assume we have a good month or so before that would normally happen anyway with a point release.

**Comment by kyrofa** [comment] 2019-09-30 15:04
Thanks for the heads up, @the-sane-- I agree.

**Comment by bakharzy** [comment] 2020-02-01 22:09
Hi,
I am receiving the same error whenever I change the tab between different apps:
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/richdocuments
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/tasks
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/notes
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/text
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/calendar

Was there any solution?

**Comment by kyrofa** [comment] 2020-02-01 22:51
@bakharzy this is [a bug in upstream Nextcloud](https://github.com/nextcloud/server/issues/13556). We're awaiting a fix.

**Comment by bakharzy** [comment] 2020-02-02 11:26
I am receiving the same error whenever I change the tab between different apps:
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/richdocuments
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/tasks
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/notes
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/text
ResourceLocator can not find a web root (root: /var/snap/nextcloud/18204/nextcloud/extra-apps/calendar

Was there any solution?

**Comment by bakharzy** [comment] 2020-02-02 11:52
Thanks @kyrofa for the quick reply. Yes, I also noticed the error does not cause any issues. However, I still have problem with the text editor toolbar not showing up for .txt files. It shows up for .md file.

**Comment by szaimen** [comment] 2020-02-02 11:54
> Thanks @kyrofa for the quick reply. Yes, I also noticed the error does not cause any issues. However, I still have problem with the text editor toolbar not showing up for .txt files. It shows up for .md file.

This is by design.

**Comment by kyrofa** [comment] 2020-02-02 17:55
You're in good company @bakharzy, that expectation bit me as well.

**Comment by richjsouth** [comment] 2020-02-12 08:00
Hi- just  adding to this.  Has anyone noticed this causing problems with the 'News' app?  My feeds haven't updated for 5 days even though they were working fine before that.  I was really enjoying getting my RSS through Nextcloud but thinking I'll have to go back to feedly unless this can be fixed.  I'm on version 18-2020-02-12 as of today but it stopped around Friday.  I'm still new to Nextcloud and Snaps so I don't know how I can help troubleshoot this but it's become a breaking problem for me.

**Comment by nickvergessen** [comment] 2020-09-03 11:38
can people please try if https://github.com/nextcloud/server/pull/22550/files solves the issue for them?

**Comment by pachulo** [comment] 2020-09-14 16:18
After updating to the 19.0.3snap1 version, I'm not seeing these errors on the logs anymore when accesing the Calendar or the Tasks applications. Thanks @nickvergessen !!

**Closed** 2020-09-14 16:40 UTC
Labels: upstream
