### ISSUE TITLE
Not possible to enable LDAP

### ISSUE THREAD

**Issue by haglo** [nextcloud/nextcloud-snap#417] opened 2018-01-18 08:09 UTC
i have installed nextcloud 12.0.4 with snap on ubuntu 16.04.
I want to active the app: “LDAP user and group backend”
The app is shown in the app-panel, but it is not possible to activate it.
It is greyed out

![unbenannt-1](https://user-images.githubusercontent.com/513155/35087079-341a32f6-fc2f-11e7-8ba2-227f2042f828.png)

With the command "nextcloud.occ app:enable user_ldap"  i get the following error:
[Exception]
App "LDAP user and group backend" cannot be installed because the following dependencies are not fulfilled: The library ldap is not available.

How can i add the "library ldap" to snapcraft.yaml?

**Comment by kyrofa** [comment] 2018-01-19 19:01
Dupe of #117. Proposed fix is #411, please test that out to see if it solves this for you.

**Closed by kyrofa** 2018-01-19 19:01 UTC
