### ISSUE TITLE
Background image change

### ISSUE THREAD

**Issue by corwin78** [nextcloud/nextcloud-snap#414] opened 2018-01-12 09:19 UTC
Hello guys, such silly issue - I can't change background picture for the login screen. Other theming options are working fine. After uploading new background picture, I can see that it is located in theming folder on the server, but logins screen picture remains default. Interesting is, that in the mobile app for Android I can see new picture used for menu background.

So, this is really low priority, but would be nice have it solved ;-)

**Comment by kyrofa** [comment] 2018-01-12 18:23
This is a dupe of #394. I'm afraid it's a regression from v11 to v12 that we need to investigate. More details on that issue (I'll close this one).

**Closed by kyrofa** 2018-01-12 18:23 UTC
