### ISSUE TITLE
Samba won't connect (NC Snap 11.0.3.snap2-rc1)

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/nextcloud-snap#272] opened 2017-05-12 18:56 UTC
Env: NC-Snap nextcloud  11.0.3snap2-rc1  1318  nextcloud  -
Device: Ubuntu Snappy / RPi2 with the Nextcloudboximage
Linux ubuntu-standard 4.4.0-1017-raspi2 #23-Ubuntu SMP Thu Jun 30 21:50:40 UTC 2016 armv7l armv7l armv7l GNU/Linux

Issue:
 it doesn't recognize my SMB shares, while my primary Nextcloud works with the identical settings. (they are in the same VPN).

Unfortunately the nextcloudbox stopped logging since 30.April, I don't know why.

It only shows a "red icon" and won't tell my why it refuses working.

smbclient -L shows me that the ncbox reaches the share:

```
Domain=[WORKGROUP] OS=[Windows 6.1] Server=[Samba 4.3.11-Ubuntu]

        Sharename       Type      Comment
        ---------       ----      -------
        print$          Disk      Printer Drivers
        Storage         Disk      Net Storage Device
        IPC$            IPC       IPC Service (ubuntu-gamestore server (Samba, Ubuntu))
Domain=[WORKGROUP] OS=[Windows 6.1] Server=[Samba 4.3.11-Ubuntu]

        Server               Comment
        ---------            -------
        UBUNTU-GAMESTOR      ubuntu-gamestore server (Samba, Ubuntu)

        Workgroup            Master
        ---------            -------
        WORKGROUP

```
additional to that, this version tells me that is has issues with webdav, but it works normally.

`Dein Webserver ist noch nicht hinreichend für Datei-Synchronisation konfiguriert, da die WebDAV-Schnittstelle vermutlich nicht funktioniert.`

**Comment by kyrofa** [comment] 2017-05-12 19:55
@pachulo, would you mind taking a look at this?

**Comment by devz3r0** [comment] 2017-05-13 08:12
@kyrofa @pachulo i think i found the reason, Apparmor is blocking it:
if you tail -f /var/log/syslog and trying to run a try, you get:
So you need to add some capabilities or so-

```
May 13 08:10:33 ubuntu-standard kernel: [3091411.993223] audit: type=1400 audit(1494663033.429:1374): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/local/sbin/" pid=12423 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ou                                                                            id=0
May 13 08:10:33 ubuntu-standard kernel: [3091411.993535] audit: type=1400 audit(1494663033.433:1375): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/local/bin/" pid=12423 comm="find" requested_mask="r" denied_mask="r" fsuid=0 oui                                                                            d=0
May 13 08:10:33 ubuntu-standard kernel: [3091411.993740] audit: type=1400 audit(1494663033.433:1376): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/sbin/" pid=12423 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May 13 08:10:33 ubuntu-standard kernel: [3091411.997040] audit: type=1400 audit(1494663033.433:1377): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/sbin/" pid=12423 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May 13 08:10:33 ubuntu-standard kernel: [3091411.997481] audit: type=1400 audit(1494663033.437:1378): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/bin/" pid=12423 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May 13 08:10:33 ubuntu-standard kernel: [3091411.997768] audit: type=1400 audit(1494663033.437:1379): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/games/" pid=12423 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
May 13 08:10:33 ubuntu-standard kernel: [3091411.998037] audit: type=1400 audit(1494663033.437:1380): apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/local/games/" pid=12423 comm="find" requested_mask="r" denied_mask="r" fsuid=0 o                                                                            uid=0
May 13 08:10:46 ubuntu-standard kernel: [3091425.409519] audit: type=1400 audit(1494663046.849:1381): apparmor="ALLOWED" operation="mknod" profile="/usr/sbin/smbd" name="/run/samba/msg.lock/12439" pid=12439 comm="smbd" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
May 13 08:10:46 ubuntu-standard kernel: [3091425.409668] audit: type=1400 audit(1494663046.849:1382): apparmor="ALLOWED" operation="open" profile="/usr/sbin/smbd" name="/run/samba/msg.lock/12439" pid=12439 comm="smbd" requested_mask="wc" denied_mask="wc" fsuid=0 ouid=0
May 13 08:10:46 ubuntu-standard kernel: [3091425.409826] audit: type=1400 audit(1494663046.849:1383): apparmor="ALLOWED" operation="truncate" profile="/usr/sbin/smbd" name="/run/samba/msg.lock/12439" pid=12439 comm="smbd" requested_mask="w" denied_mask="w" fsuid=0 ouid=0
May 13 08:10:46 ubuntu-standard kernel: [3091425.414101] audit: type=1400 audit(1494663046.853:1384): apparmor="ALLOWED" operation="unlink" profile="/usr/sbin/smbd" name="/run/samba/msg.lock/12439" pid=12439 comm="smbd" requested_mask="d" denied_mask="d" fsuid=0 ouid=0
```

**Comment by pachulo** [comment] 2017-05-13 19:35
Hi!

First of all thanks for testing this @devz3r0!

Second: I'm using the Ubuntu Core installation in my RbPi3 to test this, and I'm getting the "red icon" error when trying to add an external storage with SMB. I can also see the same DENIES that you with snappy-debug:

```
pachulo@localhost:~$ sudo /snap/bin/snappy-debug.security scanlog nextcloud
kernel.printk_ratelimit = 0
= AppArmor =
Time: May 13 18:22:38
Log: apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/local/sbin/" pid=6258 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /usr/local/sbin/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: May 13 18:22:38
Log: apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/local/bin/" pid=6258 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /usr/local/bin/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: May 13 18:22:38
Log: apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/sbin/" pid=6258 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /usr/sbin/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: May 13 18:22:38
Log: apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/sbin/" pid=6258 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /sbin/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: May 13 18:22:38
Log: apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/bin/" pid=6258 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /bin/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: May 13 18:22:38
Log: apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/games/" pid=6258 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /usr/games/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON

= AppArmor =
Time: May 13 18:22:38
Log: apparmor="DENIED" operation="open" profile="snap.nextcloud.php-fpm" name="/usr/local/games/" pid=6258 comm="find" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /usr/local/games/ (read)
Suggestion:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
```
But I think that those find commands are not related with the error, what do you think @kyrofa?

When going to the logging functionality of NC (index.php/settings/admin/logging) I can see this when trying to connect an external folder in SMB:

```
Exception: Invalid configuration
/snap/nextcloud/1318/htdocs/apps/files_external/lib/config.php - line 230: OCA\Files_External\Lib\Storage\SMB->__construct(Array)
/snap/nextcloud/1318/htdocs/apps/files_external/lib/Controller/StoragesController.php - line 255: OC_Mount_Config getBackendStatus('\\OCA\\Files_Exte...', Array, false, true)
/snap/nextcloud/1318/htdocs/apps/files_external/lib/Controller/GlobalStoragesController.php - line 179: OCA\Files_External\Controller\StoragesController->updateStorageStatus(Object(OCA\Files_External\Lib\StorageConfig), true)
[internal function] OCA\Files_External\Controller\GlobalStoragesController->update(1, 'smb-test', 'smb', 'password globa...', Array, Array, Array, Array, 100, true)
/snap/nextcloud/1318/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/snap/nextcloud/1318/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files_External\Controller\GlobalStoragesController), 'update')
/snap/nextcloud/1318/htdocs/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files_External\Controller\GlobalStoragesController), 'update')
/snap/nextcloud/1318/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Files_Exter...', 'update', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/snap/nextcloud/1318/htdocs/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/snap/nextcloud/1318/htdocs/lib/base.php - line 1010: OC\Route\Router->match('/apps/files_ext...')
/snap/nextcloud/1318/htdocs/index.php - line 40: OC handleRequest()
{main}
```

And in the [documentation about this functionality](https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage_configuration_gui.html) I've seen this note:

> A non-blocking or correctly configured SELinux setup is needed for these backends to work. Please refer to the SELinux Configuration.

But I'm getting the same errors with the snap installed in devmode:

`snap install nextcloud --candidate --devmode`

So I'm not really sure what it could be...I will follow up tomorrow!

**Comment by pachulo** [comment] 2017-05-13 23:02
Well, I did some more tests:

- In my computer (amd64 arch with Ubuntu 16.04) the samba share works if I install the snap in devmode.

@kyrofa how could I debug the problem with confinement?

**Comment by kyrofa** [comment] 2017-05-13 23:18
> how could I debug the problem with confinement?

I suggest installing snappy-debug: `sudo snap install snappy-debug`. Run it like `sudo snappy-debug.security scanlog` in one terminal, and in another exercise the confined nextcloud snap in such a way that you see samba fail. Take a look at the snappy-debug output and it'll make suggestions. If you paste the output here I can help troubleshoot.

**Comment by pachulo** [comment] 2017-05-14 11:36
The results for `sudo snappy-debug.security scanlog` are the same that those that I put in my first comment.

Anyway, I found that I was configuring the external storage support app incorrectly: before I can connect to the share I have to save an empty user and an empty password (because my share is configured to accept guests) in the global credentials. Then the share connects OK, at least in my computer with the amd64 snap; in the rbpi3 with Ubuntu Core I can't make it work. I don't really know what is going on...

**Comment by kyrofa** [comment] 2017-05-15 14:54
> The results for sudo snappy-debug.security scanlog are the same that those that I put in my first comment.

Haha, that's what I get for reading stuff on my phone. Sorry, had a pretty packed Mother's Day weekend :) .

So it seems to work on amd64, but not on the rpi3? I'm taking a closer look at this this morning.

**Comment by pachulo** [comment] 2017-05-15 15:08
> So it seems to work on amd64, but not on the rpi3? I'm taking a closer look at this this morning. I agree that the find denials seem non-fatal, but indicative of an issue (e.g. perhaps it can't find the client).

Yeah, I also thought that they might indicate an issue, but when I got it working in amd64 (devmode and normal) but not in the rpi3 (Ubuntu Core), I was back to square one...

**Comment by kyrofa** [comment] 2017-05-15 19:00
Not done debugging yet, but I have an update:

- Verified samba works fine on amd64 for v11.0.3snap2-rc1
- Verified samba doesn't work on rpi2 for v11.0.3snap2-rc1
    - Verified that I also got a "webdav is broken dummy" message, saw PHP-FPM segfaulting in the log
    - Saw PHP also segfaulting when trying to add samba share, so suspect that is the cause
- v11.0.3snap1 does NOT have "webdav broken" message, PHP does not segfault.

I'm in sanity check mode now: currently rebuilding the snap locally without the redis upgrade to see if that could have caused issues.

**Comment by kyrofa** [comment] 2017-05-15 21:00
Another update:

- Using the older redis changed nothing: I still got segfaults. But only once I tried to add the share, at which point I started getting segfaults on the external storage page (showing the red square) as well as getting the "broken webdav" warning (also segfaulting, for the same reason I assume). As soon as I deleted the samba shares in the external storage app the errors (and segfaults) went away.

At this point I'm starting to think the samba PHP module is behaving badly on armhf. I'd really like to get the redis upgrade out there though, so I'm going to have to revert the samba feature and release without it.

**Comment by kyrofa** [comment] 2017-05-15 21:20
Indeed, back on v11.0.3snap2-rc1, added external storage via local path just fine, no segfaults, no broken webdav.

**Comment by pachulo** [comment] 2017-05-16 15:54
> Using the older redis changed nothing: I still got segfaults. But only once I tried to add the share, at which point I started getting segfaults on the external storage page (showing the red square) as well as getting the "broken webdav" warning (also segfaulting, for the same reason I assume). As soon as I deleted the samba shares in the external storage app the errors (and segfaults) went away. So that was just a rabbit hole artifact of my testing process.

Just a pair of questions @kyrofa :
* Where do you get segfaults? Do you mean the 503 that the Web App returns?
* Where do you get the "broken webdav" messages?

**Comment by kyrofa** [comment] 2017-05-16 16:17
> Where do you get segfaults? Do you mean the 503 that the Web App returns?

Yeah, you'll actually see the php-fpm workers dying with signal 11's in `/var/snap/nextcloud/current/php/php-fpm.log`.

> Where do you get the "broken webdav" messages?

On the main admin page, the status checker says it (the thing that complains about using HTTP instead of HTTPS, etc.).

**Comment by kyrofa** [comment] 2017-12-12 23:29
I'm going to go ahead and close this. Seems that we're unable to get it working. If work is resumed here, feel free to re-open.

**Closed by kyrofa** 2017-12-12 23:29 UTC
