### ISSUE TITLE
Link to Collabora requires pretty URL

### ISSUE THREAD

**Issue by mokkin** [nextcloud/nextcloud-snap#1634] opened 2021-02-03 23:03 UTC
#### Describe the bug
Link to Collabora requires pretty URL

#### To Reproduce
1. Click on "built in CODE Server in admin panel"
2. Try to follow the link to Collabora Online
3. "The requested URL was not found on this server."

#### Expected behavior
Link working

#### OS/snapd/snap version
Ubuntu 20.04.2

    $ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  20.0.6snap1  26049  latest/stable  nextcloud✓  -

and:

    $ snap version
snap    2.48.2
snapd   2.48.2
series  16
ubuntu  20.04
kernel  5.4.0-65-generic

#### Screenshots
![grafik](https://user-images.githubusercontent.com/2938748/106820577-de35a400-667b-11eb-9aea-185ef5b5c895.png)

related to https://github.com/nextcloud/nextcloud-snap/issues/412

**Comment by kyrofa** [comment] 2021-02-03 23:09
I'd say that's a bug in collabora for hard-coding something than is optional more than a bug in the snap. Otherwise it's a dupe of #412.

**Closed by kyrofa** 2021-02-03 23:09 UTC
