### ISSUE TITLE
Add support for HTTP2

### ISSUE THREAD

**Issue by jfha73** [nextcloud/nextcloud-snap#1026] opened 2019-05-24 18:35 UTC
Hey guys,

I just checked the folder for Apache modules and it doesn't have the http2 module in it, would you please add it?

I'm trying to sell your product to my manager to replace IBM Aspera, but he says the speed is not nearly as fast as Aspera, I know HTTP2 is still not as fast as FASP, but at least is faster than http1.1

Thanks,

**Comment by Guillaume99** [comment] 2019-05-24 20:23
you can try:
sudo snap set nextcloud apache.http2=true
don't know if you can compare to FASP...

**Comment by pachulo** [comment] 2019-05-25 15:25
There was a pull request, but it's author closed it for lack of time to maitain it: https://github.com/nextcloud/nextcloud-snap/pull/578

@Guillaume99 that option will not work till that is implemented.

**Comment by pachulo** [comment] 2019-05-25 15:32
Besides, this is a duplicate of https://github.com/nextcloud/nextcloud-snap/issues/298

**Closed by pachulo** 2019-05-25 15:32 UTC
