### ISSUE TITLE
Apps disabled after update to 11.0.1

### ISSUE THREAD

**Issue by AlexanderPlaza** [nextcloud/nextcloud-snap#190] opened 2017-01-22 05:11 UTC
Hello, love the project however ran into an interesting bug.

So I have been using this snap on an install of Ubuntu Server 64 Bit 16.04. This installation has been running lately with no problems. I was logged in as root on the nextcloud portal while in the apps menu when the system had restarted. Please note I was not installing or uninstalling any apps while this occurred.

When I signed back in, all the previously installed apps were still installed but disabled. Resulting in loss of test bookmarks and test contacts. Is there any logs I can provide that can explain why this occurred and why the data was deleted from the app even though it was just disabled and not uninstalled?

Cheers

(Edit: I am running the latest Snap Available, 11.0.1 (Stable)

**Comment by kyrofa** [comment] 2017-01-22 05:29
Version 11.0.1snap1 was literally _just_ released (a few hours ago), which means I doubt this has anything to do with a system restart, but the fact that your snap just automatically updated. Part of the update is to run `occ upgrade`, which for some reason unknown to me disables apps when running the migrations. However, you should be able to simply re-enable them with no loss of data-- I've never seen data lost as part of this process.

**Comment by AlexanderPlaza** [comment] 2017-01-22 05:50
@kyrofa Yeah I just looked through the logs and found:

Debug	core	starting upgrade from 11.0.0.10 to 11.0.1.2	2017-01-21T22:41:13-0600

So that makes perfect sense, however any of the past upgrades have never disabled my apps. This is the first time I have seen this behaviour. But I have only been using the apps since 11.0.0 was released as a snap.

I have re-enabled but I have noticed I am missing contacts from my contacts app. Luckily just been using test contacts so it isn't that big of a deal but still weird.

Another thing I have noticed is Root has lost permission to change this value.
![image](https://cloud.githubusercontent.com/assets/16193999/22180387/652145a0-e034-11e6-8f5b-040103e3006b.png)

**Comment by AlexanderPlaza** [comment] 2017-01-22 07:27
> I have no explanation for that. In fact, the contacts app is one of my manual test cases. Do you see anything in the log explaining this?

Here is the log activity that is showing up in the main Root portal. (Is there another place I should be looking?)
```
Info	updater	\OC\Updater::resetLogLevel: Reset log level to Warning(2)	2017-01-21T22:41:28-0600
Info	updater	\OC\Updater::maintenanceDisabled: Turned off maintenance mode	2017-01-21T22:41:28-0600
Info	updater	\OC\Updater::updateEnd: Update successful	2017-01-21T22:41:28-0600
Info	updater	\OC\Updater::finishedCheckCodeIntegrity: Finished code integrity check	2017-01-21T22:41:28-0600
Info	updater	\OC\Updater::startCheckCodeIntegrity: Starting code integrity check...	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::info: Repair info: No mounts updated	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Fix potential broken mount points	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Add preview cleanup background jobs	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::info: Repair info: Repair step already executed	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Add move avatar background job	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Move .step file of updater to backup location	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Repair unmerged shares	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Remove shares of a users root folder	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::finishProgress	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::startProgress: Starting ... Fix permissions so avatars can be stored again (2)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Fix permissions so avatars can be stored again	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::finishProgress	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::startProgress: Starting ... Remove old (< 9.0) calendar/contact shares (4)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Remove old (< 9.0) calendar/contact shares	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Remove old share propagation app entries	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Repair invalid shares	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Repair outdated OCS IDs	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::info: Repair info: Removed 0 unneeded "{DAV:}getetag" entries from properties table.	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Remove getetag entries in properties table	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::step: Repair step: Drop old background jobs	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::finishProgress	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: gallery_photos (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: gallery_albums (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: contacts_cards_properties (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: contacts_cards (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: contacts_addressbooks (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: clndr_repeat (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: clndr_share_calendar (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: clndr_share_event (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: clndr_objects (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: clndr_calendars (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: sharing (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: queuedtasks (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: principals (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: principalgroups (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: pictures_images_cache (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: permissions (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: media_users (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: media_songs (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: media_sessions (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: media_artists (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: media_albums (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: log (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: locks (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: gallery_sharing (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: fscache (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: foldersize (1)	2017-01-21T22:41:18-0600
Info	updater	\OC\Repair::advance: Drop old database table: file_map (1)	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::advance: Drop old database table: calendar_share_event (1)	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::advance: Drop old database table: calendar_share_calendar (1)	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::advance: Drop old database table: calendar_objects (1)	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::advance: Drop old database table: calendar_calendars (1)	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::startProgress: Starting ... Drop old database tables (31)	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::step: Repair step: Drop old database tables	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::info: Repair info: 0 tags with no entries have been removed.	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::info: Repair info: 0 tag entries for deleted tags have been removed.	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::info: Repair info: 0 tags for delete files have been removed.	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::info: Repair info: 0 tags of deleted users have been removed.	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::step: Repair step: Clean tags and favorites	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::info: Repair info: ETags have been fixed for 0 files/folders.	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::step: Repair step: Generate ETags for file where no ETag is present.	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::info: Repair info: Asset cache cleared.	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::step: Repair step: Remove asset cache	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::step: Repair step: Repair legacy storages	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::step: Repair step: Repair mime types	2017-01-21T22:41:17-0600
Info	updater	\OC\Repair::step: Repair step: Repair MySQL collation	2017-01-21T22:41:17-0600
Info	updater	\OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: spreed	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: files_reader	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: direct_menu	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: contacts	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: calendar	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: bookmarks	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: audioplayer	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: apporder	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::dbUpgrade: Updated database	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::dbUpgradeBefore: Updating database schema	2017-01-21T22:41:13-0600
Info	updater	\OC\Repair::info: Repair info: lucene_status table does not exist -> nothing to do	2017-01-21T22:41:13-0600
Info	updater	\OC\Repair::step: Repair step: Repair duplicate entries in oc_lucene_status	2017-01-21T22:41:13-0600
Info	updater	\OC\Repair::step: Repair step: Repair SQLite autoincrement	2017-01-21T22:41:13-0600
Info	updater	\OC\Repair::step: Repair step: Repair MySQL collation	2017-01-21T22:41:13-0600
Info	updater	\OC\Repair::step: Repair step: Repair MySQL database engine	2017-01-21T22:41:13-0600
Debug	core	starting upgrade from 11.0.0.10 to 11.0.1.2	2017-01-21T22:41:13-0600
Info	updater	\OC\Updater::maintenanceEnabled: Turned on maintenance mode	2017-01-21T22:41:13-0600
```

> That value has never been changeable, I'm afraid.

I am fairly sure I changed that before to 10GB before the move to 11.0.x since the default was for sure smaller than 10GB. However if it's not changeable that won't be a big deal.

**Comment by kyrofa** [comment] 2017-01-23 20:28
Yeah none of that looks unusual to me. Perhaps this is a question best asked to the maintainer of the Contacts app.

**Comment by kyrofa** [comment] 2017-01-23 20:32
Also, I learned all about why the apps aren't re-enabled:

> **\<kyrofa\>** Hey all. Why does `occ upgrade` disable apps?
> **\<kyrofa\>** Perhaps more to the point: why does `occ upgrade` disable apps and not re-enable them when finished?
> **\<SchrodingersScat\>** 3rd party apps, idk, so they don't conflict?
> **\<kyrofa\>** SchrodingersScat, conflict with what?
> **\<kyrofa\>** SchrodingersScat, note that enabling them again after the fact works fine
> **\<kyrofa\>** SchrodingersScat, more explicitly, `occ upgrade` disables incompatible snaps, then updates them, but doesn't re-enable them
> **\<SchrodingersScat\>** kyrofa: yes, that sounds normal.
> **\<kyrofa\>** SchrodingersScat, what would be the downside of enabling them after they were updated?
> **\<SchrodingersScat\>** everything

**Comment by kyrofa** [comment] 2017-01-23 21:05
Note that we can use `--no-app-disable` when running `occ upgrade`, but from the code it seems the ramifications are that no apps are updated during the upgrade. I'm not sure what makes for a better experience.

**Comment by kyrofa** [comment] 2017-01-23 21:09
I learned a bit more in the owncloud room: `occ upgrade` disables _all_ 3rd party apps by design, because sometimes apps have issues with newer versions of the core. They want an upgrade to leave you with a guaranteed-to-work system, so they disable the 3rd party apps and leave it to you to re-enable them one-by-one in order to isolate any problems.

**Comment by AlexanderPlaza** [comment] 2017-01-24 04:41
That does make sense to ensure the core system will work after an upgrade. Can we put this information in the wiki somewhere? This way other people won't be surprised that it is disabled.

Just a thought but is there a way to prevent the auto update from happening? To postpone it until it's accepted on the root portal, or even via command line? Because if a 3rd party app is needed, and it isn't compatible right away, administrators/users can hold it back until the 3rd party app is updated. 

That all being said however, is there any clues as to why disabling the app would remove test data? Should I move the contacts missing into a separate issue?

Thanks for your work with this.

**Comment by bahbarnett** [comment] 2017-03-05 02:12
I was just bit by this, but:

1) I can't find the calendar app or contact app to re-enable.  They are MIA in the Apps 'enabled' or 'not enabled' pane

2) I can find ZERO documentation after reading the upgrade pages, manual upgrade page, and searching on Google for > 30 minutes -- as to, just what on earth I am supposed to do?!

3) Nothing is available in logs, nothing is said in the app anywhere, I don't see how to remove the apps manually via the apps/ dir, because there are a large number of files/config files there

How on earth do you fix this?  That is, without spending hours and hours searching for info, documentation, reading bug reports?

Is the goal of NextCloud to have every single user come to this bug, to even find out about this?

I don't get it.  This is bizarre.  What am I missing?

**Comment by bahbarnett** [comment] 2017-03-05 02:18
Wait.

So, when I enable apps they show up in 'enabled'.  When apps aren't enabled, they don't show up in 'disabled'?

This strangeness is the source of my pain. :/

1) Nextcloud says 'disabling apps'
2) I log in
3) Apps aren't in disabled

I don't understand why 'official' apps are sometimes in 'disabled' and sometimes not.

There should be:

- all apps are in either enabled or disabled

OR

- get rid of 'disabled', or call it something else (like, 'generic' apps or something?!)

**Comment by bahbarnett** [comment] 2017-03-05 02:21
Additional clarity -- if the 'disabled' pane is only for manually disabled apps, then why weren't my manually disabled apps in there?

**Comment by kyrofa** [comment] 2017-03-05 02:29
@bahbarnett I'm afraid I can't help you with the design decisions made by Nextcloud itself, I just package the snap. Please feel free to log a bug against the upstream project.

**Comment by kyrofa** [comment] 2017-03-05 02:31
@bahbarnett you say you just hit this issue, and yet no updates have been released for quite some time (just about to, though). Has your machine just been offline the whole time, or did you hit a different problem?

**Comment by bahbarnett** [comment] 2017-03-05 03:21
Ah, I see the confusion.  11.0.2 was released less than a week ago.  This was an 11.0.1 to .2 upgrade.

**Comment by kyrofa** [comment] 2017-03-05 04:30
@bahbarnett 11.0.2 of upstream Nextcloud was released. The snap version typically lags by a week or two. 11.0.2 of the snap will be released early next week. So you either just updated to .1 or something else is happening.

**Comment by bahbarnett** [comment] 2017-03-05 11:21
Sure -- anyhow, point is, this is inherent behaviour upstream.  EG, this entire bug, snap version or not, is expected behaviour.

Apologies for not noticing the -snap after landing from a Google search, but I'd say this bug should be closed as 'this is the way upstream does it', as you say.

**Comment by oparoz** [comment] 2017-03-05 11:31
With NC12, official apps will be re-enabled after and update.

**Closed by oparoz** 2017-03-05 11:31 UTC
