### ISSUE TITLE
nextcloud.occ: command not found

### ISSUE THREAD

**Issue by j-grim** [nextcloud/nextcloud-snap#1064] opened 2019-07-10 21:23 UTC
Bug is in Debian 10. Trying to run the following:
usr@blah :/var/snap/nextcloud# sudo nextcloud.occ config:system:set overwritehost --value="example.com" 
I get the following
sudo: nextcloud.occ: command not found

Running Nextcloud 15.0.10snap1
and:
Snap version 2.39.3

Here are the logs:
https://pastebin.com/KGWvWX8p

**Comment by j-grim** [comment] 2019-07-10 21:27
update: was able to run it via abspath: 
sudo /snap/bin/nextcloud.occ config:system:set overwritehost --value="example.net"

**Comment by kyrofa** [comment] 2019-07-10 21:38
Yeah, the docs assume `/snap/bin` is in your `$PATH` like it is in Ubuntu. I'm surprised it's not in Debian, you might consider asking in #snappy on Freenode why that is, perhaps it's a bug in the snapd packaging there.

I'll go ahead and close this since it's not a bug in the snap, but feel free to continue discussion here.

**Closed by kyrofa** 2019-07-10 21:38 UTC

**Comment by j-grim** [comment] 2019-07-11 17:57
Going to post something to them and see what they say.
