### ISSUE TITLE
LDAP user and group backend

### ISSUE THREAD

**Issue by hopggsy76** [nextcloud/nextcloud-snap#332] opened 2017-08-01 09:00 UTC
LDAP user and group backend is greyed out as an option in the Snap,

**Comment by pachulo** [comment] 2017-08-01 19:02
It is greyed out because the LDAP support is not included in the snap. An issue is opened here: https://github.com/nextcloud/nextcloud-snap/issues/117

Which is your use case?

**Comment by kyrofa** [comment] 2018-01-02 15:48
Closing as it's a dupe of #117.

**Closed by kyrofa** 2018-01-02 15:48 UTC
