### ISSUE TITLE
Nextcloud installed as snap uses way too much RAM and is extremelly slow

### ISSUE THREAD

**Issue by wUFr** [nextcloud/nextcloud-snap#513] opened 2018-04-17 09:38 UTC
*copy pasted from original report https://github.com/nextcloud/server/issues/9201 (:*

### Steps to reproduce
1. Install nextcloud through Snap
2. Open web interface or download/upload any files through desktop client

### Expected behaviour
Less RAM usage? Faster loading?

### Actual behaviour
Loading of web interface is sometimes extremelly slow (even up to 20 seconds), mostly on first load. Generating previews of images is super slow too and whole nextcloud uses ALL the ram it has most of the time (10GB atm), which compared to others being able to run it on RasPi and similar low-end hardware seems a bit weird at least.

### Server configuration

**Operating system**: Ubuntu server 16.04.4

**Web server:** Whatever nextcloud snap installs
**Database:** Whatever nextcloud snap installs
**PHP version:** Whatever nextcloud snap installs

**Extra info:** Hyper-V VM with 8 threads assigned from AMD FX-8300, 10GB DDR3 ram, 250GB HDD

**Nextcloud version:** 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install of both Ubuntu and nextcloud

**Where did you install Nextcloud from:** Snap (following this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-16-04)

... i would fill in remaining info, but this occured even after clean install of Nextcloud through snap and im trying to find out, if others have similar issues.

I think i will just reinstall whole VM and do good old manual install of apache, mariaDB and nextcloud itself, becouse it looks like Snap itself is the hardware hog :'(

**Comment by wUFr** [comment] 2018-04-17 09:43
This is without even doing anything (browsing or syncing) on Nextcloud... 

![stats](https://user-images.githubusercontent.com/10975377/38862090-55e77588-4234-11e8-861d-f153a125f8e6.PNG)
![htop](https://user-images.githubusercontent.com/10975377/38862091-5603832c-4234-11e8-81af-c8fc97e09f5b.PNG)

**Comment by wUFr** [comment] 2018-04-21 19:52
Issue "resolved" by installing webserver and nextcloud itself manually, guess Snap is not right way to go rn

**Comment by dragon2611** [comment] 2018-04-28 21:34
I'd argue that's not a resolution as whilst it fixes your problem the issue with the snap being slow is not resolved.

**Comment by wUFr** [comment] 2018-04-29 21:41
ye, but i no longer have snap VM running, so i cant even continue to test it

**Comment by wUFr** [comment] 2018-04-29 21:43
btw first load of web interface being slow as hell may have been caused by network issues (some hyper-v incompatibility) - appeared in manual install as well

**Comment by dragon2611** [comment] 2018-04-29 21:52
It's not the hyper-V networking as I can reproduce on Proxmox (KVM) happened on Ubuntu 16.04, still happens on 18.04 as well.

I moved the VM to my other host to move NC to SSD storage and a more modern CPU but it didn't help, sometimes it can be lightning fast others it can take 30s+ to load.

**Comment by wUFr** [comment] 2018-04-29 22:51
well i guess i can reopen it

**Comment by kyrofa** [comment] 2018-04-29 23:07
(although this doesn't sound like a problem just with the snap, no?)

**Comment by wUFr** [comment] 2018-04-30 05:46
well normal installation of Nextcloud has its own issues, but at least it does not use ALL the ram ALL the time (:

**Comment by irvinyip** [comment] 2018-05-10 01:08
I have the same issue, RAM is not used up by response is extremely slow that when I sync with only 1 testing client with 10000 files, after slow-syncing ~3000, it'll disconnect like crash on client (but nothing happened on server, looks normal without CPU peak). Then connect again to sync in slow speed. I have similar hardware to run a manual install nextcloud, it's 10 times faster on both sync and web GUI response. My hardware is 4CPU AMD A10, 8G ram allocated but keeping staying at ~3GB (RAM usage is normal I think). I have also tried to snap set nextcloud php.memory-limit=512M, but doesn't help, still crashing (disconnecting)...

**Comment by kyrofa** [comment] 2018-05-14 01:40
Just judging from htop, this looks like a mysql issue. Unfortunately, I can't pretend to be a mysql tuning pro, so I'll need to do some research here. Anyone here know much about that?

**Comment by pachulo** [comment] 2018-05-14 22:00
@kyrofa it's been more that year and four revisions since the last update of nextcloud-snap mysql (5.7.18): https://dev.mysql.com/doc/relnotes/mysql/5.7/en/ so I guess it won't hurt to update to the latest one and see if we're lucky.

**Comment by kyrofa** [comment] 2018-05-14 22:06
@pachulo I doubt that will help, but might as well update it. Want to revive that old PR you made? You can patch with `override-pull` these days, so we don't need to use my fork anymore.

**Comment by r4co0n** [comment] 2018-05-15 13:18
@kyrofa, did you consider asking MySQL upstream to implement your patch, maybe via a build flag? If I understood what you are doing there correctly, this is necessary for all/many snaps that use MySQL server, so we might get this merged?

**Comment by dragon2611** [comment] 2018-05-15 13:51
Ended up reinstalling nextcloud directly on the VM rather than in a snap and it's much faster using php 7.2 and mariadb 10.2.

I did use the following as I have a fair bit of ram
[mysqld]
max_allowed_packet=128M
query_cache_size = 512M

**Comment by solick** [comment] 2018-05-17 05:48
Same issue. Update from nextcloud 12 to 13 (snap, Raspberry Pi 3) slows down ui and sync. Tested with multiple clients on multiple Macs and also with ipad. If this is a mysql issue it would be interesting to know what have changed between 12 and 13.

**Comment by IvanTurgenev** [comment] 2018-06-12 03:50
insane amount of ram laugable

**Comment by kyrofa** [comment] 2018-06-12 16:20
> @kyrofa, did you consider asking MySQL upstream to implement your patch, maybe via a build flag? If I understood what you are doing there correctly, this is necessary for all/many snaps that use MySQL server, so we might get this merged?

Yeah, no love. They [asked a few questions](https://github.com/mysql/mysql-server/pull/65), I answered, and then zero progress. Thus the fork.

> It might also be useful to reevaluate the choice of MySQL over MariaDB as it could behave differently when confined in a snap.

That migration doesn't sound particularly fun.

**Comment by kyrofa** [comment] 2018-06-12 18:13
I've been taking a look at this. I too see this:

![screenshot from 2018-06-12 11-09-39](https://user-images.githubusercontent.com/946674/41308585-27afc624-6e31-11e8-95b0-ee4aec5f5849.png)

However, what we're seeing here are not separate processes all using 1% of my RAM, but several _threads_ all _sharing_ 1% of my RAM. From the htop manpage:

> H    Hide user threads: on systems that represent them differently than
            ordinary processes (such as recent NPTL-based systems),  this  can
            hide  threads  from userspace processes in the process list. (This
            is a toggle key.)

So, I hit capital H, and now I see:

![screenshot from 2018-06-12 11-12-20](https://user-images.githubusercontent.com/946674/41308693-809f471e-6e31-11e8-910e-8bd46586abad.png)

I actually don't think this is a problem at all. At least, it has nothing to do with mysql.

> If this is a mysql issue it would be interesting to know what have changed between 12 and 13.

That's the thing: absolutely nothing changed regarding mysql.

**Comment by kyrofa** [comment] 2018-06-12 18:19
@wUFr note that the original htop image you shared has most of your ram as yellow, which is cache, not in active use.

**Comment by IvanTurgenev** [comment] 2018-06-12 18:47
check out atop show my vmcom over my vmlim with just nextcloud running

**Comment by kyrofa** [comment] 2018-06-12 18:50
@IvanTurgenev that's not very useful without seeing the actual data.

**Comment by IvanTurgenev** [comment] 2018-06-12 18:58
welp i just delete it all and installed a seafile docker, sorry will try next time if i see some new improvements, should try testing on a 512 ram vps, nextcloud normal installation on a 512 should work fine

**Comment by kyrofa** [comment] 2018-06-12 19:02
You were running it on less than 512MB? Yikes, yeah I don't suggest anything less than 1GB.

**Comment by IvanTurgenev** [comment] 2018-06-12 19:04
welp the docs say it should run on 128 ram

**Comment by kyrofa** [comment] 2018-06-12 19:05
What docs?

**Comment by IvanTurgenev** [comment] 2018-06-12 19:06
https://docs.nextcloud.com/server/13/admin_manual/installation/system_requirements.html

**Comment by kyrofa** [comment] 2018-06-12 19:07
Ah, maybe for sqlite. That's not realistic, sorry.

**Comment by joshmorel** [comment] 2018-07-13 18:30
I had no issue (small usage) with 512MB on non-snap with Ubuntu 16, MariaDB, PHP 7.0. I had to periodically clear cache manually but that was it. I'm running now on 1GB without issues but interested in switching to snap (don't need to, but it looks like a great go forward option for single node installs).

Although it may not fix the issue 100% - I'm :+1: :+1:  for MariaDB over MySQL. From my general understanding It's all upsides no downsides. Might be worth trying the two options with otherwise identical specs side-by-side (I'm willing to take some time to experiment).

**Comment by kyrofa** [comment] 2018-07-13 21:10
@joshmorel I have yet to hear a single actual reason for switching to mariadb over mysql beyond "it's not Oracle." Which actually is a pretty good reason, but not enough to go to the work of seamlessly migrating thousands of installs.

This issue does not appear to be a real issue, so I'm going to close.

**Closed by kyrofa** 2018-07-13 21:10 UTC

**Comment by esbeeb** [comment] 2021-03-27 22:04
The Shift-H while within htop was key, much appreciated, @kyrofa .
