### ISSUE TITLE
Upgrade to version 14.0.5snap1 fails on Nextcloud Box

### ISSUE THREAD

**Issue by aptanet** [nextcloud/nextcloud-snap#843] opened 2019-01-12 11:29 UTC
My Nextcloud Box (official install with a Raspberry Pi 2) has just decided to upgrade to 14.0.5snap1 from  13.0.8snap1. I noticed because the clients were no longer connecting and when I checked it was in maintenance mode. Given that the Raspberry Pi isn't a power house I have left this for about 12 hours (from first noticing, through finding maintenance mode enabled and then overnight) to see if it was working with the database or files before enabling again. Unfortunately this is not the case.
I have tried "sudo nextcloud.occ maintenance:mode --off" to disable maintenance mode, but this gives the error:
"The files of the app (updatenotification) were not replaced correctly. Make sure it is a version compatible with the server."
I have also reverted back and forced a refresh again, but the same thing happens.
Suggestions for diagnostics and / or fixes welcome. I will feed back if / when I find out more.

**Comment by jlicher** [comment] 2019-01-12 11:32
The same for me. What to do to solve the problem?

**Comment by aptanet** [comment] 2019-01-12 11:58
I have a fix, although I haven't sorted out the updatenotification app yet (it isn't listed in either enabled or disabled apps). The Nextcloud instance is back up and running with an accessible web interface again though. The procedure I used was:

**_Disclaimer: This has only been tested on my own Nextcloud Box once, make sure you are backed up :-)_**

Disable the updatenotification app with:
`sudo nextcloud.occ app:disable updatenotification`

This got the web interface working again with the prompt to start the upgrade process (apps, database, etc.). I decided to do this from the command line with:
`sudo nextcloud.occ upgrade`

My first login to the web was a bit slow, but that is likely the clients connecting up all at the same time as all appears to be working again now. As I said I haven't looked into what to do about the updatenotification app yet, but thought this info may be helpful.

Another thing to note is that I got a whole raft of the following error:
`ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.`
It appears this isn't an issue from a quick web search, although I've not done an extensive investigation.

**Comment by eldertfrancke** [comment] 2019-01-12 11:58
See #838 
You can disable this app with the following command:
`nextcloud.occ app:disable updatenotification`

Next you can trigger the update manual and manual disable the maintenance mode, with the following commands:
```
nextcloud.occ upgrade
nextcloud.occ maintenance:mode --off

```

**Comment by jlicher** [comment] 2019-01-12 12:04
thank you, i worked for me too.

**Comment by joshmorel** [comment] 2019-01-12 13:30
Worked for me too on Ubuntu VM. What does updatenotification do, is it needed at all anymore?

**Comment by eldertfrancke** [comment] 2019-01-12 13:34
@joshmorel See https://github.com/nextcloud/nextcloud-snap/issues/838#issuecomment-453744930 It's not needed, because of the auto update function of snap.

**Comment by kyrofa** [comment] 2019-01-12 14:42
Dupe of #838

**Closed by kyrofa** 2019-01-12 14:42 UTC
