### ISSUE TITLE
Enable HTTP / 2

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/nextcloud-snap#997] opened 2019-05-14 09:47 UTC
on a raspbian system I configured the nextcloud properly and I noticed a remarkable speed of opening site and nextcloud pages enabling the http / 2 module on apache.

Can you do it on snap nextcloud?

if possible implement it?

I read a github about a year ago but I don't know if the jobs are stopped.

**Comment by PnjDbq** [comment] 2019-05-14 16:47
See issue #298. There’s also a PR referenced on that issue with good history.

**Comment by kyrofa** [comment] 2019-05-15 12:27
Yeah, dupe of #298.

**Closed by kyrofa** 2019-05-15 12:27 UTC
