### ISSUE TITLE
Question: Backing Up Snap

### ISSUE THREAD

**Issue by stone212** [nextcloud/nextcloud-snap#597] opened 2018-06-09 03:50 UTC
Looking at the doc to back up nextcloud in general (https://docs.nextcloud.com/server/12/admin_manual/maintenance/backup.html) it is not clear how to approach backup of the snap.

Specifically:

- the mySQL of the snap may not be the same as the one I can access on the server in general

- where are the "config, data and theme folders"?

- Can I just back up /var/snap/nextcloud/current and have everything I need?

Thank you.

**Comment by r4co0n** [comment] 2018-06-09 19:18
This is a recurring question, please see the discussion of relevant issues in issue #489.
It can be done, but the current approach requires some manual work.

**Comment by kyrofa** [comment] 2018-08-27 15:29
Please see the directions on #688 for how to help us test a new feature adding exactly this!

This is a dupe of #489 which is a dupe of #185, so I'm going to go ahead and close it.

**Closed by kyrofa** 2018-08-27 15:29 UTC
