### ISSUE TITLE
External memory

### ISSUE THREAD

**Issue by MANFahrer-GF** [nextcloud/nextcloud-snap#901] opened 2019-02-18 20:18 UTC
External memory

External storage allows external storage services and devices to be included as second storage devices in Nextcloud. Users can be allowed to integrate their own external storage services.

"smbclient" is not installed. It is not possible to add "SMB / CIFS", "SMB / CIFS with OC login". Please contact the administrator for installation.

NextCloud: 15.0.4 and 15.0.2

**Comment by kyrofa** [comment] 2019-02-22 16:37
Dupe of #60, we can't seem to get it working across architectures I'm afraid. Any help would be appreciated.

**Closed by kyrofa** 2019-02-22 16:37 UTC
