### ISSUE TITLE
Be able to remove 'index.php' from URL

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/nextcloud-snap#1382] opened 2020-06-15 10:36 UTC
I want to remove the '/index.php' from the cloud URL.
E.g: `https://mycloud.ddnss.de/index.php/apps/files/` --> `https://mycloud.ddnss.de/apps/files/`

The solution can be made with following two options but I can't execute the command `maintenance:update:htaccess` because the .htaccess file is read-only.
The two settings (copied from `config.sample.php`):
```
/**
 * To have clean URLs without `/index.php` this parameter needs to be configured.
 *
 * This parameter will be written as "RewriteBase" on update and installation of
 * Nextcloud to your `.htaccess` file. While this value is often simply the URL
 * path of the Nextcloud installation it cannot be set automatically properly in
 * every scenario and needs thus some manual configuration.
 *
 * In a standard Apache setup this usually equals the folder that Nextcloud is
 * accessible at. So if Nextcloud is accessible via "https://mycloud.org/nextcloud"
 * the correct value would most likely be "/nextcloud". If Nextcloud is running
 * under "https://mycloud.org/" then it would be "/".
 *
 * Note that the above rule is not valid in every case, as there are some rare setup
 * cases where this may not apply. However, to avoid any update problems this
 * configuration value is explicitly opt-in.
 *
 * After setting this value run `occ maintenance:update:htaccess`. Now, when the
 * following conditions are met Nextcloud URLs won't contain `index.php`:
 *
 * - `mod_rewrite` is installed
 * - `mod_env` is installed
 *
 * Defaults to ``''`` (empty string)
 */
'htaccess.RewriteBase' => '/',

/**
 * For server setups, that don't have `mod_env` enabled or restricted (e.g. suEXEC)
 * this parameter has to be set to true and will assume mod_rewrite.
 *
 * Please check, if `mod_rewrite` is active and functional before setting this
 * parameter and you updated your .htaccess with `occ maintenance:update:htaccess`.
 * Otherwise your nextcloud installation might not be reachable anymore.
 * For example, try accessing resources by leaving out `index.php` in the URL.
 */
'htaccess.IgnoreFrontController' => false,
```

Maybe this can be a default setting or even a command like `nextcloud.<a command name here>` like `nextcloud.import or nextcloud.removable-media`. Or maybe a snap variable.

However, would this be possible?

**Comment by kyrofa** [comment] 2020-06-15 15:32
Dupe of #412, definitely one our more-requested issues, it's just been difficult to figure out how to properly pull it off and no one has had time to get it right.

**Closed by kyrofa** 2020-06-15 15:32 UTC
