### ISSUE TITLE
Calendar: ResourceLocator can not find a web root; Upgrade: 13.0.2.1 -> 13.0.4.0

### ISSUE THREAD

**Issue by Matttthias** [nextcloud/nextcloud-snap#625] opened 2018-06-27 10:33 UTC
Hi,

since upgrade of my Nextcloud-Snap Installation from 13.0.2.1 -> 13.0.4.0 I find following error messages in the protocol log. 

> ResourceLocator can not find a web root (root: /var/snap/nextcloud/7658/nextcloud/extra-apps/calendar, file: index.php/css/calendar/e34c-7d44-app.min.css, webRoot: , throw: true)

In addition the synchronization of my calendar between nextcloud and my smartphone does not work anymore. Both automatic and manual triggering of synchronization results in another entry of above mentioned error.

Applying the saying "rebood is always good", I disabled, enabled the nextcloud snap and activated, deactivated the calendar app, to no avail.

My Nextcloud-Snap-Installation is roughly more than a year old.

Search of similar issues here and at nextcloud forum provided me with the impression, that likelyhood of a snap-system issue seems to be high, so I raise this as new issue here.

Thanks for looking into this issue,

**Comment by kyrofa** [comment] 2018-06-29 19:23
Huh, well that's interesting. I've been noticing some weirdness with my calendar as well, wonder if this is what's behind it. Let me investigate.

**Comment by derhagen** [comment] 2019-01-14 21:08
I get the same message on 14.0.5
Collabora throws some similar errors, too:
> ResourceLocator can not find a web root (root: /var/snap/nextcloud/10791/nextcloud/extra-apps/richdocuments, file: index.php/css/richdocuments/d9e1-5e0b-templatePicker.css?v=7f934ed194f97f40cb7506602924cd01, webRoot: , throw: true)

**Comment by kyrofa** [comment] 2019-10-10 22:14
I'm going to pretend that this is a dupe of #902, even though this one was logged first.

**Closed by kyrofa** 2019-10-10 22:14 UTC
