### ISSUE TITLE
Raspberry Pi 3 B+ nextcloud

### ISSUE THREAD

**Issue by coderInCape** [nextcloud/nextcloud-snap#502] opened 2018-04-06 00:35 UTC
Hiya, 
I'm just wondering if this image will work on the new Raspberry Pi 3 B+ model ?
The faster ethernet speed in the new model is so tempting

**Comment by JamesBream** [comment] 2018-05-01 14:49
Should work fine with Ubuntu Core on the 3B+ considering not much has changed from the 3.

**Comment by r4co0n** [comment] 2018-06-11 07:45
Closing this as it seems answered and not a bug.

Please note that questions like this will probably get a faster answer and a bigger audience at [https://help.nextcloud.com/](https://help.nextcloud.com/).

**Closed by r4co0n** 2018-06-11 07:45 UTC
