### ISSUE TITLE
Add a way to raise the PHP memory limit

### ISSUE THREAD

**Issue by Tech4Freelancers** [nextcloud/nextcloud-snap#130] opened 2016-11-20 08:00 UTC
I hit a very unpleasant roadblock when trying to synchronize a big folder (approx. 23 GB in size) with many small files. The Box exhausts the memory allocated to PHP and the client stop synchronizing because it encountered an internal server error. Unfortunately the php.ini file is part of the /snap folder, which is read-only and its permissions cannot be edited, even by root.

**Comment by kyrofa** [comment] 2016-11-21 19:40
The [admin manual](https://docs.nextcloud.com/server/10/admin_manual/configuration_files/big_file_upload_configuration.html) doesn't mention that as something that should be necessary, at least not that I've found. Are you sure you're not simply exhausting all of the box's RAM?

**Comment by Tech4Freelancers** [comment] 2016-11-21 19:43
Pretty sure. I have a consistent 350-390 memory usage with two users logged in.
I'm gonna try and see if I can edit the php.ini files externally and post the results.

21 nov 2016, 20:40 +0100, Kyle Fazzari <notifications@github.com>, ha scritto:

**Comment by Guillaume99** [comment] 2016-12-23 08:22
at least for now, can we increase the memory limit to 256M ?
see : https://help.nextcloud.com/t/nc-box-memory-exhausted/4183/6
(see end of the thread on memory consumption ...)

**Comment by kyrofa** [comment] 2017-01-09 18:34
Doing this for all platforms is a bad idea-- it barely runs on the pi as-is.

**Comment by kyrofa** [comment] 2017-10-25 23:29
Oh my, I'm so sorry folks, I duplicated this issue. I forgot we already had one! Anyway, this will be fixed in the next release, but I'll close this as a dupe of #374 since that's the one I'm tracking.

**Closed by kyrofa** 2017-10-25 23:29 UTC
