### ISSUE TITLE
 sudo nextcloud.enable-https lets-encrypt fails

### ISSUE THREAD

**Issue by andreaswarnaar** [nextcloud/nextcloud-snap#605] opened 2018-06-12 19:15 UTC
Hi,

Im setting up a nexcloud snap but i cannot generate a letsencrypt certificate. 
Attempting to obtain certificates... error running certbot:

An unexpected error occurred:
IOError: [Errno 13] Permission denied: '/etc/letsencrypt/cli.ini'
Please see the logfile '/tmp/tmpkjdNfx' for more details.

Any advice how to fix this?

Andreas

**Comment by kyrofa** [comment] 2018-06-12 19:19
Yeah, dupe of #569, workaround over there. You can refresh to beta if you want the pre-release fix.

**Closed by kyrofa** 2018-06-12 19:19 UTC

**Comment by andreaswarnaar** [comment] 2018-06-12 19:40
Thx!
