### ISSUE TITLE
Unable to get Nextcloud to work with SMB in snap installation

### ISSUE THREAD

**Issue by dlauer** [nextcloud/nextcloud-snap#420] opened 2018-01-20 17:45 UTC
I installed Nextcloud via snap on Ubuntu 16.04, and subsequently installed smbclient, php-smbclient php-smb and any other smb-related package I can find. I can confirm that smbclient is present on the system (/usr/bin/smbclient). Yet Nextcloud Admin still has the error message, under external storage:
"smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login" is not possible. Please ask your system administrator to install it.

I'm also unable to access local SMB mounts, although I'm not sure if that's a permission problem or not.

**Comment by kyrofa** [comment] 2018-01-20 19:39
Dupe of #60. Indeed, this is missing from the snap. We tried to add it, but it's broken on ARM, so we reverted it. More details in #60.

**Closed by kyrofa** 2018-01-20 19:39 UTC

**Comment by fpernice518** [comment] 2018-08-03 05:09
I'd like to second this issue . I'm running on x86_64

**Comment by ujtwr** [comment] 2018-08-26 21:34
I found a solution.
When the php has only smbclient command - no libsmbclient or php smbclient module -, the php uses smbclient command by using 'shell_exec' function.

apps/files_external/3rdparty/icewind/smb/src/System.php:32
$this->smbclient = trim(which smbclient);

shell_exec function refer to enviroment variables, so we have to set "PATH".
but my case, enviromental variables was cleared because php-fpm config file has "clear_env = yes". I changed "clear_env" of php-fpm config file from "YES" to "NO". the nextcloud became to be able to access smb directory.

**Comment by pachulo** [comment] 2018-08-26 21:55
@ujtwr did you tested that on armhf arch? Because what we tried was working on x86_x64 & i386 but not there.

**Comment by ujtwr** [comment] 2018-08-27 15:11
@pachulo sorry, I just tested on the x86_x64

**Comment by adriangn** [comment] 2018-08-27 19:56
@ujtwr How exactly did you set the enviromental variable? I have the same issue on x86_x64 and I'm no being able to fix it

**Comment by kyrofa** [comment] 2018-08-27 19:57
@adriangn given that the php config is read-only, I assume @ujtwr build a customized snap.
