### ISSUE TITLE
How to increase max file upload size and timeout

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [nextcloud/nextcloud-snap#586] opened 2018-05-30 06:28 UTC
I installed nextcloud 13 via snap on Ubuntu 16.04.

I have to upload huge files. Now I would like to increase the max upload size (now at 10G) and the timeout (now at 3600 seconds). Where do I do that with snap? Is it even possible?

**Comment by PnjDbq** [comment] 2018-05-30 15:17
I'm looking at an old (and open) ticket, and it looks like upload size is defined in the Apache config.  Which, in a Snap, is read-only.

See https://github.com/nextcloud/nextcloud-snap/issues/77

**Comment by kyrofa** [comment] 2018-05-30 15:22
Yeah, this is a dupe of #77. Please read through that issue, we're actually not entirely sure where the limit is coming from.

**Closed by kyrofa** 2018-05-30 15:22 UTC

**Comment by eespitiarea** [comment] 2019-06-28 14:53
Since snap manages the app, one is not able to directly commit changes, it has to do through snap itself. Given the options and commands available in this app, one can just replace underscores with dashes after php in the name of the parameter, like:

- php.upload-max-filesize
- php.post-max-size
- php.max-input-time
- php.max-execution-time

And then for the upload size: `snap set nextcloud php.post-max-size=16G` or `sudo` if is system-wide.

**Comment by Snuggle** [comment] 2019-07-25 02:11
@eespitiarea I think you have just fixed an issue that has annoyed me and made my Nextcloud instance seem near-unusuable for something like half a year.

Thank you so much! 😊 💞

**Comment by veeableful** [comment] 2020-03-24 02:07
Just in case anyone is still struggling like I was when Nextcloud is behind Nginx, it turns out I also needed to set `client_max_body_size = 16G;` in my Nginx config file on the `server` or `location` block :sweat_smile:

**Comment by mauriciolazo** [comment] 2020-04-18 14:36
> Just in case anyone is still struggling like I was when Nextcloud is behind Nginx, it turns out I also needed to set `client_max_body_size = 16G;` in my Nginx config file on the `server` or `location` block 😅
Thank you for this, you just saved me hours of troubleshooting. I'm using Nginx as a public reverse proxy for my home servers.

**Comment by Fuseteam** [comment] 2021-02-07 17:04
> Since snap manages the app, one is not able to directly commit changes, it has to do through snap itself. Given the options and commands available in this app, one can just replace underscores with dashes after php in the name of the parameter, like:
> 
>     * php.upload-max-filesize
> 
>     * php.post-max-size
> 
>     * php.max-input-time
> 
>     * php.max-execution-time
> 
> 
> And then for the upload size: `snap set nextcloud php.post-max-size=16G` or `sudo` if is system-wide.

this is exactly what I was looking for, I wish these little snap commands like these were documented in one place

**Comment by Fuseteam** [comment] 2021-02-07 18:37
> `client_max_body_size = 16G;`

this errors out for me I had to do `client_max_body_size 16G;`

**Comment by veeableful** [comment] 2021-02-08 02:03
> > `client_max_body_size = 16G;`
> 
> this errors out for me I had to do `client_max_body_size 16G;`

Oops yeah, I don't know where that equal sign came from :rofl:. Thanks!

**Comment by kyrofa** [comment] 2021-02-08 16:13
> Since snap manages the app, one is not able to directly commit changes, it has to do through snap itself. Given the options and commands available in this app, one can just replace underscores with dashes after php in the name of the parameter

> this is exactly what I was looking for, I wish these little snap commands like these were documented in one place

They're not documented because they _don't exist_. Every such configuration is documented in [the configuration section of the README](https://github.com/nextcloud/nextcloud-snap#configuration). Anything not documented there simply doesn't exist.

**Comment by Fuseteam** [comment] 2021-02-08 16:20
> > Since snap manages the app, one is not able to directly commit changes, it has to do through snap itself. Given the options and commands available in this app, one can just replace underscores with dashes after php in the name of the parameter
> 
> > this is exactly what I was looking for, I wish these little snap commands like these were documented in one place
> 
> They're not documented because they _don't exist_. Every such configuration is documented in [the configuration section of the README](https://github.com/nextcloud/nextcloud-snap#configuration). Anything not documented there simply doesn't exist. You can run `snap set nextcloud please-do-what-i-want=true` and it won't actually do anything. I think @eespitiarea was trying to make a suggestion for something we could support, not trying to provide reference documentation.

both `php.upload-max-filesize` and `php.post-max-size` I was looking in docs.nextcloud.com when I was searching for those settings

**Comment by Fuseteam** [comment] 2021-02-08 16:31
oh i stand corrected snap doesn't say if it is creating a variable my bad :x

**Comment by kyrofa** [comment] 2021-02-08 16:34
> I have successfully set both afaict

That's what I was trying to say-- you can literally set anything you want, and that doesn't matter. What matters is what the snap actually _reads_ and pays attention to. This is not one of my favorite snap features-- I can't provide a configuration schema, which makes this not very user-friendly because it makes it impossible to say "oh you tried to set something the snap doesn't support." All we can do is check the ones we DO support, because the [`configure` hook](https://github.com/nextcloud/nextcloud-snap/blob/master/src/hooks/bin/configure) is run whenever you run `snap set nextcloud`. You can take a pass through there and see what exactly is supported.

**Comment by Fuseteam** [comment] 2021-02-08 16:37
> > I have successfully set both afaict
> 
> That's what I was trying to say-- you can literally set anything you want, and that doesn't matter. What matters is what the snap actually _reads_ and pays attention to. This is not one of my favorite snap features-- I can't provide a configuration schema, which makes this not very user-friendly because it makes it impossible to say "oh you tried to set something the snap doesn't support." All we can do is check the ones we DO support, because the [`configure` hook](https://github.com/nextcloud/nextcloud-snap/blob/master/src/hooks/bin/configure) is run whenever you run `snap set nextcloud`. You can take a pass through there and see what exactly is supported.

yeah thanks for the heads up, that is indeed issue with snap that should be fixed. is there any chance these configs can be added to the nextcloud docs? that's the first place I looked before going through github issues. it didn't cross my mind to check the readme

**Comment by kyrofa** [comment] 2021-02-08 16:38
Yeah I don't see why not. Where would you have expected to see them?

**Comment by Fuseteam** [comment] 2021-02-08 16:42
> Yeah I don't see why not. Where would you have expected to see them?

somewhere around here maybe? https://docs.nextcloud.com/server/21/admin_manual/installation/index.html

**Comment by stefanod83** [comment] 2023-07-03 08:07
> Just in case anyone is still struggling like I was when Nextcloud is behind Nginx, it turns out I also needed to set `client_max_body_size 16G;` in my Nginx config file on the `server` or `location` block 😅

in 'http' section ;)
https://linuxhint.com/what-is-client-max-body-size-nginx/
