### ISSUE TITLE
20.0.2 Update - extremely slow 

### ISSUE THREAD

**Issue by nunomgsantos80** [nextcloud/nextcloud-snap#1569] opened 2020-12-05 16:06 UTC
After updating, access was extremely slow. 
I can't find any justification for that.

Someone with the same problem or with knowledge of it?

Regards.

**Comment by Pilzinsel64** [comment] 2020-12-05 16:18
Yes, I have exactly the same problem. The response is very very slow. Not only the web, also on the mobile client (Android).

**Comment by nunomgsantos80** [comment] 2020-12-05 16:23
Hi, yes in mobile app also.

**Comment by gaborbuzasi** [comment] 2020-12-05 16:32
I have the same issue, it has updated this morning and access through Web and Mobile (iOS) is incredibly slow. It takes about 1 minute to process an HTTP request, however certain JSON side requests made by the web app seem to respond quickly.

**Comment by pheiduck** [comment] 2020-12-05 17:20
Confirmed

**Comment by pheiduck** [comment] 2020-12-05 17:21
And /tmp goes full

**Comment by eganonoa** [comment] 2020-12-05 17:49
Had the very same issue on two separate Nextcloud instances (work and personal), but have just resolved it.  The Nextcloud snap update breaks the Collabora Online edition's connection to the built-in Code server. If you disable both apps (i.e. Collabora and the CODE server), you will find that the performance springs right back to life. This fixed it in both instances.  

There is no Collabora Online or CODE server app update available.  So I suspect we'll have to make do without for now (OnlyOffice works fine).

**Comment by nunomgsantos80** [comment] 2020-12-05 18:00
> Had the very same issue on two separate Nextcloud instances (work and personal), but have just resolved it. The Nextcloud snap update breaks the Collabora Online edition's connection to the built-in Code server. If you disable both apps (i.e. Collabora and the CODE server), you will find that the performance springs right back to life. This fixed it in both instances.
> 
> There is no Collabora Online or CODE server app update available. So I suspect we'll have to make do without for now (OnlyOffice works fine).

Thks, it worked.

**Comment by Pilzinsel64** [comment] 2020-12-05 18:05
But anyway, it seems that the text editor app seems to be broken. I guess that's a part of the bugs in v20.0.2.

**Comment by gaborbuzasi** [comment] 2020-12-05 18:23
> Had the very same issue on two separate Nextcloud instances (work and personal), but have just resolved it. The Nextcloud snap update breaks the Collabora Online edition's connection to the built-in Code server. If you disable both apps (i.e. Collabora and the CODE server), you will find that the performance springs right back to life. This fixed it in both instances.
> 
> There is no Collabora Online or CODE server app update available. So I suspect we'll have to make do without for now (OnlyOffice works fine).

How did you figure that this is causing the slowdown?

**Comment by eganonoa** [comment] 2020-12-05 18:45
> > Had the very same issue on two separate Nextcloud instances (work and personal), but have just resolved it. The Nextcloud snap update breaks the Collabora Online edition's connection to the built-in Code server. If you disable both apps (i.e. Collabora and the CODE server), you will find that the performance springs right back to life. This fixed it in both instances.
> > There is no Collabora Online or CODE server app update available. So I suspect we'll have to make do without for now (OnlyOffice works fine).
> 
> @eganonoa How did you figure that this is causing the slowdown?

@gaborbuzasi It was helpful that I had two completely separate Nextcloud snap installs exhibiting the same behaviour and a bunch of other things on servers performing great, as it allowed me to rule out server-specific things and work on the assumption that it was the update. From there is was as simple as running htop on the two servers, browse through the portals and watch for similar patterns. That showed huge spikes on "extra-apps" and the appimage collabora that gets installed with the app. Then if you go to your settings > Collabora page you will see an error in connecting to the CODE server. Seems clear that Nextcloud was constantly trying to establish a connection that was broken and that that was causing CPU load spikes. Turn off the apps, performance resumes, so problem diagnosed.

If you look around a bit, one of the things that gets recommended a lot with Nextcloud is to run top/htop and observe what's happening. The portal's analytics don't seem to be granular enough to pick up a lot of things like very quick RAM or CPU spikes.  And the logging can be full of junk if you've not set log-level to something that basically eliminates everything but full on major errors (which then leaves a lot out).  So top/htop and just watching as you use, seems to be a good way to diagnose things.

**Comment by nunomgsantos80** [comment] 2020-12-05 18:49
@eganonoa thks for the help and explanation.

**Comment by eganonoa** [comment] 2020-12-05 19:50
> @eganonoa thks for the help and explanation.

@nunomgsantos80 My pleasure

**Comment by kyrofa** [comment] 2020-12-05 21:09
>  The Nextcloud snap update breaks the Collabora Online edition's connection to the built-in Code server. If you disable both apps (i.e. Collabora and the CODE server), you will find that the performance springs right back to life. This fixed it in both instances.

Interesting, all we did was ship an update to 20.0.2, is there a known upstream bug about this?

**Comment by kyrofa** [comment] 2020-12-05 21:11
>  But sadly I can't find the root problem. Sadly, I also can't revert, for some reason the revision is gone on my storage.

@Pilzinsel64, can I see the output of `snap list nextcloud --all`, please?

**Comment by kyrofa** [comment] 2020-12-05 21:15
Sounds like it's happening in [Docker as well](https://help.nextcloud.com/t/nextcloud-20-0-2snap2-interface-incredibly-slow/100304/4?u=kyrofa), so definitely sounds like an upstream issue.

**Comment by LyimeS** [comment] 2020-12-05 22:51
it was taking so long to process the HTTP request I got worried for a moment, thinking something happened to the server. but yeah, disabling Collabora Online and Collabora CODE Server "solved" the problem. thanks :)

**Comment by BostonEnginerd** [comment] 2020-12-06 00:29
For anyone coming here to try to fix this, the two modules which needed to be disabled are "richdocuments" and "richdocumentscore".

```
sudo snap run nextcloud.occ app:disable richdocuments
sudo snap run nextcloud.occ app:disable richdocumentscore
```

**Comment by arifeman** [comment] 2020-12-06 12:16
> For anyone coming here to try to fix this, the two modules which needed to be disabled are "richdocuments" and "richdocumentscore".
> 
> ```
> sudo snap run nextcloud.occ app:disable richdocuments
> sudo snap run nextcloud.occ app:disable richdocumentscore
> ```

I can confirm this fix worked for me! :) Thank you so much @BostonEnginerd!

**Comment by JMoVS** [comment] 2020-12-06 16:11
I have the same slow-down, but am not using Collabora in any way - I see a lot of php-fm processes taking a lot of CPU...

**Comment by mschwrdtnr** [comment] 2020-12-07 08:52
> I have the same slow-down, but am not using Collabora in any way - I see a lot of php-fm processes taking a lot of CPU...

I get this warnings every second...

Debug | files_sharing | /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead. |   | 2020-12-07T09:51:45+0100
-- | -- | -- | -- | --
Debug | contacts | /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead. |   | 2020-12-07T09:51:45+0100

**Comment by eganonoa** [comment] 2020-12-07 13:16
> Sounds like it's happening in [Docker as well](https://help.nextcloud.com/t/nextcloud-20-0-2snap2-interface-incredibly-slow/100304/4?u=kyrofa), so definitely appears to be an upstream issue.

I've opened an issue in Nextcloud/richdocuments (https://github.com/nextcloud/richdocuments/issues/1282). 

At least for now we have the solution:  disable collabora and the code server either via the web-interface admin settings (if you can get there), or via the server terminal as above.

**Comment by Pilzinsel64** [comment] 2020-12-07 14:20
> @Pilzinsel64, can I see the output of `snap list nextcloud --all`, please?

Sure, here:
![grafik](https://user-images.githubusercontent.com/23138465/101361823-c6ba8480-389f-11eb-9bba-ddd8e8c967e1.png)

**Comment by kyrofa** [comment] 2020-12-07 16:40
@Pilzinsel64 you have two revisions there, the one for snap1 and the one for snap2. Are you saying you were unable to revert to snap1 from snap2, or simply that the revert did nothing to solve the issue?

**Comment by kyrofa** [comment] 2020-12-07 17:43
Confirmed, this makes the snap unusable. Nothing interesting in the logs during usage that doesn't relate to collabora. When trying to open a document I see this though:

```
{"reqId":"FX5iHBU58fJlpkNjGQsY","level":3,"time":"2020-12-07T17:38:50+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"richdocuments","method":"GET","url":"/index.php/apps/richdocuments/index?fileId=11&requesttoken=AEyf86%2BIbFplFbZnaNJpmAjUL4WrtY98go6EYe6v%2BNM%3D%3ANDjKqtXyKw8dW9QFX7gBt2nlH%2FTYhd447v7HL6jXteE%3D","message":{"Exception":"Exception","Message":"Could not find urlsrc in WOPI","Code":0,"Trace":[{"file":"/var/snap/nextcloud/24828/nextcloud/extra-apps/richdocuments/lib/TokenManager.php","line":210,"function":"getUrlSrc","class":"OCA\\Richdocuments\\WOPI\\Parser","type":"->","args":["application/vnd.openxmlformats-officedocument.wordprocessingml.document"]},{"file":"/var/snap/nextcloud/24828/nextcloud/extra-apps/richdocuments/lib/Controller/DocumentController.php","line":256,"function":"getToken","class":"OCA\\Richdocuments\\TokenManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/24828/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->","args":["*** sensitive parameter replaced ***",null]},{"file":"/snap/nextcloud/24828/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"index"]},{"file":"/snap/nextcloud/24828/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"index"]},{"file":"/snap/nextcloud/24828/htdocs/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\DocumentController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"richdocuments.document.index"}]},{"file":"/snap/nextcloud/24828/htdocs/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/richdocuments/index"]},{"file":"/snap/nextcloud/24828/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/snap/nextcloud/24828/nextcloud/extra-apps/richdocuments/lib/WOPI/Parser.php","Line":54,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.2.2"}
```

**Comment by Pilzinsel64** [comment] 2020-12-07 18:49
@kyrofa Thanks for the info. Yes I tried to revert and it did revert to snap1 but it did it fasten then normal and i didn't trust the process and tried revering it a second time. And of course this didn't work. Now I am again on snap2 because the auto update.

I can't increase the refresh retainer to more then 2 because I have only a 32gb sd card where my os is on. I want to increase that to at least 128gb soon. But thanks for the tip. I will remember till I got a bigger sd card.

**Comment by pheiduck** [comment] 2020-12-10 18:05
Issue also present in 20.0.3 :/

**Comment by kyrofa** [comment] 2020-12-10 19:39
Yeah I expect it will be until the referenced collabora issue is resolved.

**Comment by dinosmm** [comment] 2020-12-11 13:40
I have a very similar slowdown issue but mine is not fixed by disabling Collabora. Also, on my install the Web UI loads fine, but it's the elements that need to be fetched from the DB that take ages, e.g. calendar items, file listings, sharing link creation, etc. Am I having a different issue?

**Comment by kyrofa** [comment] 2020-12-14 20:20
I'm going to close this. There's nothing we can do about it in the snap, and the upstream issue isn't moving as fast as I was hoping it would. I don't see a benefit to holding this issue open. Of course, feel free to continue discussion here.

**Closed by kyrofa** 2020-12-14 20:20 UTC
Labels: upstream

**Comment by Darkknight33** [comment] 2021-06-25 07:18
Just want to thank you guys for posting a solution to this problem here. I was experiencing an approx. 30 sec delay between page loads that was not present when the NC 21.0.2 server was initially deployed via docker, and only showed up after a few restarts. Completely unexplainable until I found this issue. Disabling the two apps fixed the performance problem.

Wondering if perhaps it's not better to set the CODE & Collabora apps to disabled by default until this issue is resolved.
