### ISSUE TITLE
Nextcloud-snap is rejecting Port 80 useage after Port 443 SSL certificate added

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/nextcloud-snap#589] opened 2018-06-01 09:27 UTC
Nextcloud-snap is rejecting Port 80 usage after Port 443 SSL certificate added

In this particular setup of Nextcloud-snap, I need to also have port 80 connectivity with NC running as a tor hidden service. Is this inability to now connect to port 80 http only on the browsers end, in Nextcloud-Snap or the Domain hosting? 

During the setup and testing phases I was concurrently running clearnet regular www http port 80 domain.name connected peers and tor hidden service .onion connected peers at the same time. Now I'm unable to be able to established any port 80 connection http to .onion connected peers after adding the SSL https port 443 signed, verified certificate even with the tor browser.

Suggestions to try, test?

**Comment by r4co0n** [comment] 2018-06-03 10:04
If you enable https, Apache will only redirect http requests to https, see [here](https://github.com/nextcloud/nextcloud-snap/blob/master/src/apache/conf/ssl.conf#L74-L82).
For your particular use-case, I think I would disable https in the snap and setup another Apache instance on the host, this one would use ssl and proxy requests to the snap, the hidden service is just another `ServerName` and some configuration in `torrc`, see [here](https://tor.stackexchange.com/a/6186).
If I'm not mistaken,running your .onion host via SSL should also work, e.g., you don't **need** port 80 at all.

**Comment by r4co0n** [comment] 2018-06-11 07:43
Closing this as it seems answered and not a bug.

Please note that questions like this will probably get a faster answer and a bigger audience at [https://help.nextcloud.com/](https://help.nextcloud.com/).

**Closed by r4co0n** 2018-06-11 07:43 UTC
