### ISSUE TITLE
MySql high idle load

### ISSUE THREAD

**Issue by f-s** [nextcloud/nextcloud-snap#1416] opened 2020-07-23 07:26 UTC
#### Describe the bug
I migrated from the manual NC install to the 18/stable snap. That is away from php7.4 and postgresql to the snap. Now the server wont enter the idle state, if not in use. I get an avg. af 1.4% load, mostly caused by the mysql server.

#### To Reproduce
1. snap install nextcloud --channel=18/stable
2. watch the idle load

#### Expected behavior
No idle load. Like before with a manual NC 18 install.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

Ubuntu 20.04 LTS
18/stable

#### Logs
Well, it works without error, but the high idle load.

**Comment by kyrofa** [comment] 2020-07-23 16:56
When you had a manual NC install, how were you running the NC cron jobs? Webcron? System cron?

**Comment by f-s** [comment] 2020-07-24 09:01
Hello,

I was running the NC cron job using the system crontab.

The idle load is definitely caused by the mysql server, you can tell this by using "powertop".

@kyrofa 
Do you also have an idle load with mysql-server in an otherwise idle NC install?

Thanks,

fse

**Comment by kyrofa** [comment] 2020-07-28 17:11
>  Do you also have an idle load with mysql-server in an otherwise idle NC install?

Not really, although that could be simply because I ran it on my dev machine which is really far from idle on its own; it's possible mysql was drowned out.

**Comment by kyrofa** [comment] 2020-07-29 05:45
Try installing from the `latest/beta/tuned-mysql` channel, see if that changes anything:

    $ sudo snap install nextcloud --channel=latest/beta/tuned-mysql

Or, if you already have it installed:

    $ sudo snap refresh nextcloud --channel=latest/beta/tuned-mysql

**Comment by f-s** [comment] 2020-07-29 13:10
Thanks, I did the tuned-mysql install and the powertop output looks like this:

[mysql.txt](https://github.com/nextcloud/nextcloud-snap/files/4995018/mysql.txt)

Where "redis" can be stopped and uses some idle time, mysqld obviously is not expendable.

**Comment by kyrofa** [comment] 2020-12-03 20:08
> Thanks, I did the tuned-mysql install and the powertop output looks like this:

Given that I never saw your initial output, it's unclear if that behavior is better, worse, or no different.

**Comment by tensau** [comment] 2021-01-12 17:03
Same problem here :( this renders the snap almost useless in my case.
Did you find anything which contributes to this high load idle processes?

**Comment by f-s** [comment] 2021-01-13 09:49
@tensau 
I stopped using the Snap and I use PostgreSQL and a manual install instead, works.

**Comment by tensau** [comment] 2021-01-15 16:34
@f-s possible workaround, but no real solution.
@kyrofa can I provide logs or something alike to analyze this problem?

**Comment by tensau** [comment] 2021-01-20 07:37
Moving to the Edge-Channel seems to help - at least, it's a lot faster. (NC 21.0.0 beta6)

**Comment by brozkeff** [comment] 2021-01-21 09:23
Confirmed on latest snap 20, my home server keeps Mysql at cpuload 1 and the electricity consumption of the entire server is more than doubled just by this waste.

**Comment by kyrofa** [comment] 2021-01-22 00:09
I'm not really convinced this is an issue with the snap. The mysql config used here isn't special, and various attempts to change parameters don't seem to change anything. This might be due to servers not actually being idle at all, or mysql just working this way. My servers don't appear to be having issues, and I can't reliably fix something without duplicating it, I'm afraid.

That said, if someone else can reliably duplicate this, I'd be happy to walk you through getting a writable install setup so you can play with parameters and give us some solid recommendations. I don't recommend doing that on a production box, though.

**Comment by f-s** [comment] 2021-01-25 07:19
> I'm not really convinced this is an issue with the snap.

Any software inside a snap, is inside a snap. So any mysql snap issue, is a snap issue. Am I wrong?

**Comment by kyrofa** [comment] 2021-01-25 16:04
What I mean to say is that this seems to be how mysql behaves in and out of the snap. If the same thing happens outside the snap, I'm not confident we'll be able to fix it inside. Perhaps what I should have said is "this isn't unique to the snap."

**Comment by kyrofa** [comment] 2021-01-25 16:15
I'm going to go ahead and close. My previous offer to help someone who is seeing this through experimenting is still on the table, but barring that I don't think it's useful to continue tracking this.

**Closed by kyrofa** 2021-01-25 16:15 UTC

**Comment by f-s** [comment] 2021-01-26 08:37
yes, please close.
